### ISSUE TITLE
Briefcase fails to create macos app, Toga can run it though

### ISSUE THREAD

**Issue by tecnocris** [beeware/briefcase#113]
Templates and apps that run in toga on both windows and macos compile in briefcase on my windows 10 machine, but do not compile on briefcase on my macos machine. 

This is the code for the app I was trying to run, but the issue persists even on template 0 and 1. 
https://gist.github.com/ChristopherMay/6d8a9ab74db40925f2896dbfae82c1bb

I ran the command below in terminal and received the following traceback:

macOS/HVACCalculator.app/Contents/MacOS/HVACCalculator

Traceback (most recent call last):
  File "/Volumes/Storage/Python/beeware/hvaccalculator/macOS/HVACCalculator.app/Contents/Resources/python/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Volumes/Storage/Python/beeware/hvaccalculator/macOS/HVACCalculator.app/Contents/Resources/python/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/volumes/storage/python/beeware/hvaccalculator/macOS/HVACCalculator.app/Contents/Resources/app/hvaccalculator/__main__.py", line 1, in <module>
    from hvaccalculator.app import main
  File "/volumes/storage/python/beeware/hvaccalculator/macOS/HVACCalculator.app/Contents/Resources/app/hvaccalculator/app.py", line 4, in <module>
    from coolingsetup import cooling_window
ModuleNotFoundError: No module named 'coolingsetup'

**Comment by freakboy3742** [comment]
This appears to be a problem with specifying dependencies. Your application depends on a module named "coolingsetup", but that package hasn't been included in your application's dependencies (or, it's part of your codebase, and you haven't included it as code that needs to be packaged).

We've just landed a branch that radically alters the configuration format, so any problem you were historically seeing will definitely have different manifestations now. Closing this ticket on that basis; if you still see this problem on the new configuration format, let me know.
