### ISSUE TITLE
Missing lines in Android stack traces

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#1161]
This was reported in https://github.com/chaquo/chaquopy/issues/837, and it doesn't appear to be reproducible, but I'm posting it here for future reference.

Original stack trace from Android Studio Logcat window:
```
FATAL EXCEPTION: main
Process: com.example.myTogaTest, PID: 24703
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myTogaTest/org.beeware.android.MainActivity}: com.chaquo.python.PyException: TypeError: 'builtin_function_or_method' object is not subscriptable
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: com.chaquo.python.PyException: TypeError: 'builtin_function_or_method' object is not subscriptable
	at <python>.__main__.<module>(__main__.py:3)
	at <python>.runpy._run_code(runpy.py:86)
	at <python>.runpy._run_module_code(runpy.py:96)
	at <python>.runpy.run_module(runpy.py:224)
	at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
	at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)
	at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
	at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
	at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
	at org.beeware.android.MainActivity.onCreate(MainActivity.java:64)
	at android.app.Activity.performCreate(Activity.java:8305)
	at android.app.Activity.performCreate(Activity.java:8284)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7872) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

Stack trace shown by Briefcase:
```
-------- beginning of crash
04-01 02:56:51.856 26009 26009 E AndroidRuntime: FATAL EXCEPTION: main
04-01 02:56:51.856 26009 26009 E AndroidRuntime: Process: com.example.myTogaTest, PID: 26009
04-01 02:56:51.856 26009 26009 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myTogaTest/org.beeware.android.MainActivity}: com.chaquo.python.PyException: TypeError: 'builtin_function_or_method' object is not subscriptable
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at <python>.runpy.run_module(runpy.py:224)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at <python>.chaquopy_java.call(chaquopy_java.pyx:354)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:326)    
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at com.chaquo.python.PyObject.callAttr(PyObject.java:221)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at org.beeware.android.MainActivity.onCreate(MainActivity.java:64)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8305)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8284)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
04-01 02:56:51.856 26009 26009 E AndroidRuntime:        ... 12 more
04-01 02:56:51.875 26009 26009 I Process : Sending signal. PID: 26009 SIG: 9
```

**Comment by mhsmith** [comment]
See https://github.com/chaquo/chaquopy/issues/837 for analysis.
