### ISSUE TITLE
Test suite failing due to setuptools/pip updates

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#1195]
### Describe the bug

The Briefcase CI test suite is currently failing with a series of errors caused by recent setuptools and pip updates,.

### Steps to reproduce

1. Update pip and setuptools
2. Run the CI test suite.

### Expected behavior

Test suite should pass cleanly,

### Environment

- Operating System: macOS (any)
- Python version: any
- Software versions:
  - Briefcase: 0.3.15.dev29+g5c83de4a
  - Pip: 23.1
  - Setuptools: 67.6.1

### Logs

There are dozens of test failures, preventing CI from even collecting the test suite:
```
==============================================================================
CRITICAL: tests/test_cmdline.py
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rkm/beeware/briefcase/tests/test_cmdline.py", line 16, in <module>
    from briefcase.platforms.macOS.app import (
  File "/Users/rkm/beeware/briefcase/src/briefcase/platforms/macOS/__init__.py", line 20, in <module>
    import dmgbuild
  File "/Users/rkm/beeware/briefcase/venv3.10/lib/python3.10/site-packages/dmgbuild/__init__.py", line 1, in <module>
    from .core import build_dmg
  File "/Users/rkm/beeware/briefcase/venv3.10/lib/python3.10/site-packages/dmgbuild/core.py", line 12, in <module>
    import pkg_resources
  File "/Users/rkm/beeware/briefcase/venv3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 121, in <module>
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
DeprecationWarning: pkg_resources is deprecated as an API
```

### Additional context

The issue is that dmgbuild is using the deprecated setuptools pkg_resources API to get package resources.

**Comment by freakboy3742** [comment]
We've fixed the problem with #1196; however, that PR includes [a FIXME line](https://github.com/beeware/briefcase/blob/5af03934089fff2b291fb7b6b8d197797bee2c9c/tox.ini#L8) that can be removed once pip pushes out an updated release.
