### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by IronLung127** [beeware/briefcase#1349]
### Describe the bug

I have followed the same instructions listed over [here](https://docs.beeware.org/en/latest/tutorial/tutorial-0.html]). I tried running `briefcase new --no-input` it results in:
```
Generating a new application 'Hello Wor
[briefcase.2023_07_07-16_17_50.new.log](https://github.com/beeware/briefcase/files/11990492/briefcase.2023_07_07-16_17_50.new.log)
ld'
Using app template: https://github.com/beeware/briefcase-template, branch v0.3.14
Using existing template (sha be60e3889a819b0f9b547a21e803342f79cb868e, updated Wed Apr 12 11:07:29 2023)

Log saved to /home/ironlung/dev/logs/briefcase.2023_07_08-16_21_31.new.log

Traceback (most recent call last):
  File "/home/ironlung/.local/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/home/ironlung/.local/lib/python3.9/site-packages/briefcase/__main__.py", line 25, in main
    command(**options)
  File "/home/ironlung/.local/lib/python3.9/site-packages/briefcase/commands/new.py", line 529, in __call__
    return self.new_app(
  File "/home/ironlung/.local/lib/python3.9/site-packages/briefcase/commands/new.py", line 478, in new_app
    self.generate_template(
  File "/home/ironlung/.local/lib/python3.9/site-packages/briefcase/commands/base.py", line 835, in generate_template
    self.tools.cookiecutter(
  File "/home/ironlung/.local/lib/python3.9/site-packages/cookiecutter/main.py", line 114, in cookiecutter
    nested_template = re.search(
AttributeError: 'NoneType' object has no attribute 'group'
```

### Steps to reproduce

1. `briefcase new --no-input`
2. Now the error for me (idk for y'all)

### Expected behavior

- 

### Environment

- Operating System: Arch Linux, Kernel: 6.4.1-arch2-1 
- WindowManager: XMonad
- Python version: 3.11.3
- Software versions:
  - Briefcase: 0.3.14

### Logs

```

```

**Comment by mhsmith** [comment]
See #1347.

**Comment by rmartin16** [comment]
To work around this until Briefcase v0.3.15 is released, run this command after installing Briefcase:
```console
python -m pip install cookiecutter==2.1.1
```
