### ISSUE TITLE
ModuleNotFoundError: No module named 'toga.django'

### ISSUE THREAD

**Issue by sanjaykhanssk** [beeware/briefcase#156]
ModuleNotFoundError: No module named 'toga.django'
 * Starting Django server on localhost:8042
 * Opening browser...
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'toga.django'

**Comment by meichthys** [comment]
What version of Toga are you using? It may be worth trying toga==0.3.0.dev3

**Comment by chrda81** [comment]
I'm facing the same problem using toga==0.3.0.dev11

**Comment by freakboy3742** [comment]
We've temporarily disabled our Django backend due to the limitations in using the 0.3 branch of Toga. Closing this ticket until we're able to re-add web support.
