### ISSUE TITLE
Briefcase Android Build Fails

### ISSUE THREAD

**Issue by AsherJoju** [beeware/briefcase#1726]
### Describe the bug

I was building my project for android using briefcase and encountered this issue.

I am stll a newbie with python app dev so **Any Help Will Be Appreciated**

Issue-

distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install cffi==1.16.0 from https://files.pythonhosted.org/packages/68/ce/95b0bae7968c65473e1298efb042e10cafc7bafc14d9e4f154008241c91d/cffi-1.16.0.tar.gz#sha256=bcb3ef43e58665bbda2fb198698fcae6776483e0c4a631aa5647806c25e02cc0 (from -r requirements.txt (line 2)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command '/home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/bin/python'' finished with non-zero exit value 1

Full build messages -

*************************************************************************
** WARNING: Default system encoding is not supported                   **
*************************************************************************

    Briefcase and the third-party tools it uses only support UTF-8.

    The detected default system encoding is ISO8859-1.

    Briefcase will proceed but some console output could be corrupted and
    created files or artefacts may contain corrupted text.

    Update your system's encoding to UTF-8 to avoid issues.

*************************************************************************

[frux] Updating app metadata...
Setting main module... done

[frux] Building Android APK...

> Configure project :app
Warning: Python version 3.10 may have fewer packages available. If you experience problems, try switching to version 3.8.

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:extractDebugPythonBuildPackages

> Task :app:generateDebugPythonRequirements
Chaquopy: Installing for arm64-v8a
Looking in indexes: https://pypi.org/simple, https://chaquo.com/pypi-13.1
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting cffi==1.16.0
  Using cached cffi-1.16.0.tar.gz (512 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/bin/python /home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp32q64rxp
       cwd: /tmp/pip-install-wslqo605/cffi
  Complete output (24 lines):
  Traceback (most recent call last):
    File "/home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/lib/python3.10/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-xsyeuwzj/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-xsyeuwzj/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-xsyeuwzj/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 148, in <module>
    File "<string>", line 77, in ask_supports_thread
    File "/tmp/pip-build-env-xsyeuwzj/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/config.py", line 223, in try_compile
      self._compile(body, headers, include_dirs, lang)
    File "/tmp/pip-build-env-xsyeuwzj/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/config.py", line 128, in _compile
      self.compiler.compile([src], include_dirs=include_dirs)
    File "/tmp/pip-build-env-xsyeuwzj/site/chaquopy_monkey.py", line 72, in compile
      chaquopy_block_native("CCompiler.compile")
    File "/tmp/pip-build-env-xsyeuwzj/site/chaquopy_monkey.py", line 105, in chaquopy_block_native
      raise DistutilsPlatformError("{}: {}".format(prefix, CHAQUOPY_NATIVE_ERROR))
  distutils.errors.DistutilsPlatformError: CCompiler.compile: Chaquopy cannot compile native code
  ----------------------------------------
ERROR: Failed to install cffi==1.16.0 from https://files.pythonhosted.org/packages/68/ce/95b0bae7968c65473e1298efb042e10cafc7bafc14d9e4f154008241c91d/cffi-1.16.0.tar.gz#sha256=bcb3ef43e58665bbda2fb198698fcae6776483e0c4a631aa5647806c25e02cc0 (from -r requirements.txt (line 2)).
For assistance, please raise an issue at https://github.com/chaquo/chaquopy/issues.
Chaquopy: Exit status 1

> Task :app:generateDebugPythonRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateDebugPythonRequirements'.
> Process 'command '/home/asher/Projects/Proodle/frux/build/frux/android/gradle/app/build/python/env/debug/bin/python'' finished with non-zero exit value 1
  
  To view full details in Android Studio:
  * Click the 'Build: failed' caption to the left of this message.
  * Then scroll up to see the full output.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
2 actionable tasks: 2 executed
Building...

Error while building project.

Log saved to /home/asher/Projects/Proodle/frux/logs/briefcase.2024_04_09-18_22_14.build.log

### Steps to reproduce

I am not sure how to reproduce.

### Expected behavior

I expected it to build an Android App.

### Environment

OS - Ubuntu 22.04.4 LTS
Python - 3.10.12
Briefcase - 0.3.17

### Logs

Log File - 
[briefcase.2024_04_09-18_22_14.build.log](https://github.com/beeware/briefcase/files/14918877/briefcase.2024_04_09-18_22_14.build.log)

**Comment by rmartin16** [comment]
When packages contain native code, they must be built specifically for the Android platform. There are versions of `cffi` [available](https://chaquo.com/pypi-13.1/cffi/) for each supported version of Python...but v1.16.0 is only available for Python 3.12. So, you'll either need to change your version of Python or the version of `cffi` you're trying to install.
