### ISSUE TITLE
fails to download gradle if proxy is in use

### ISSUE THREAD

**Issue by operator000** [beeware/briefcase#1982]
### Describe the bug

  When I was following Tutorial 5 to create the Android app helloworld, I meet the following error:
```
PS C:\Users\hp\helloworld> briefcase build android

[helloworld] Updating app metadata...
Setting main module... done

[helloworld] Building Android APK...
Downloading https://services.gradle.org/distributions/gradle-8.2-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:579)
        at java.base/sun.nio.ch.Net.connect(Net.java:568)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2944)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2853)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1949)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
        at org.gradle.wrapper.Download.download(Download.java:51)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Building... errored

Error while building project.

Log saved to C:\Users\hp\helloworld\logs\briefcase.2024_09_01-17_57_53.build.log
```
  I guess this is because beeware don't support proxy now.  I can open `https://services.gradle.org/distributions/gradle-8.2-bin.zip` only when using proxy. Can I download the file manually, like mentioned in #479 ? How should I do that in detail?

  Thanks a lot.

### Steps to reproduce

1. follow the Tutorial to make a HelloWorld application
2. briefcase create android
3. briefcase build android

### Expected behavior

If you cannot open `https://services.gradle.org/distributions/gradle-8.2-bin.zip` in browser ,`briefcase build android` may also fail.

### Environment

- Operating System:Win11
- Python version:Python 3.12.3 
- Software versions:
  - Briefcase:0.3.19

### Logs
[briefcase.2024_09_01-17_57_53.build.log](https://github.com/user-attachments/files/16828492/briefcase.2024_09_01-17_57_53.build.log)

**Comment by rmartin16** [comment]
Briefcase defers to Requests' management of proxies: https://docs.python-requests.org/en/latest/user/advanced/#proxies.

Gradle says it defers proxy configuration to JVM settings: https://docs.gradle.org/current/userguide/networking.html

Elsewhere, it [describes](https://docs.gradle.org/current/userguide/build_environment.html#the_gradle_properties_file) how the `gradle.properties` file works:

> You can place the `gradle.properties` file in the root directory of your project, the Gradle user home directory (`GRADLE_USER_HOME`), or the directory where Gradle is optionally installed (`GRADLE_HOME`).
> 
> When resolving properties, Gradle first looks in the project-level `gradle.properties` file, then in the user-level `gradle.properties` file located in `GRADLE_USER_HOME`, and finally in the `gradle.properties` file located in `GRADLE_HOME`, with project-level properties taking precedence over user-level and installation-level properties.

So, I would try setting up this `gradle.properties` configuration for your proxy and trying again. It may also be possible to use the Java setting `java.net.useSystemProxies=true` to automatically use a proxy configured for your system.

**Comment by rmartin16** [comment]
For the `useSystemProxies` method, looks like this should work in `gradle.properties`:
```
systemProp.java.net.useSystemProxies=true
```
This might be something worth adding to Briefcase's default template for Android Gradle builds.

**Comment by freakboy3742** [comment]
As noted in the report, this is essentially #479. Briefcase doesn't officially support proxied downloads; this is a known limitation. Closing on that basis.
