### ISSUE TITLE
Briefcase support packages incompatible with pip 24.3

### ISSUE THREAD

**Issue by freakboy3742** [beeware/briefcase#2053]
### Describe the bug

Pip 24.3 was just released, including support for iOS as a platform.

However, Briefcase isn't currently providing a platform tag when invoking pip to select wheels. Instead, it uses a sitepackage to monkeypatch the sys, sysconfig and platform modules to make a macOS install look like iOS.

On pip <= 24.2, there is no explicit support for iOS; pip will fall back on default macOS handling, and the monkeypatch inserts enough context to force pip to load iOS wheels.

However, the new version of pip will honor the existence of `iOS` as a platform, and then requires `platform.ios_ver()` and `sys.implementation._multiarch` to generate the correct list of candidate wheels.

The current support packages don't add these shims; and as a result, iOS builds will fail.

### Steps to reproduce

1. Generate a helloworld project
2. Add `pillow` to the requires list
3. `briefcase build iOS`

An error something like the following will be generated:
```
[verifyapp] Installing requirements...
Installing app requirements for iPhone device... started
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
ERROR: Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 363, in run
    resolver = self.make_resolver(
               ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 177, in make_resolver
    return pip._internal.resolution.resolvelib.resolver.Resolver(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 58, in __init__
    self.factory = Factory(
                   ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 125, in __init__
    self._supported_tags_cache = get_supported()
                                 ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/utils/compatibility_tags.py", line 165, in get_supported
    supported.extend(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/packaging/tags.py", line 224, in cpython_tags
    platforms = list(platforms or platform_tags())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/packaging/tags.py", line 503, in ios_platforms
    _, release, _, _ = platform.ios_ver()  # type: ignore[attr-defined]
                       ^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'ios_ver'

Installing app requirements for iPhone device... errored

Unable to install requirements. This may be because one of your
requirements is invalid, or because pip was unable to connect
to the PyPI server.
```

### Expected behavior

Briefcase should be able to install wheels when pip 24.3+ is in use.

### Environment

- Operating System: macOS
- Python version: Any
- Software versions:
  - Briefcase: 0.3.20+
  - pip 24.3+

### Logs

```

```

### Additional context

On Python 3.13, `platform.ios_ver()` will *exist*, so the missing attribute error won't be raised. However, the tag that is resolved will be `ios_13_0_darwin`, which won't match any tags.

As an immediate workaround, downgrading to pip 24.2 will resolve the issue.

**Comment by freakboy3742** [comment]
The fix for this issue has been backported to the 0.3.20 branch.
