### ISSUE TITLE
Hello World fails at "subprocess.CalledProcessError: Command '['xcrun', 'xcodebuild', '-version']' returned non-zero exit status 72."

### ISSUE THREAD

**Issue by jay20162016** [beeware/briefcase#220]
```
$ python setup.py ios -s
running ios

 * Updating user code...
 * Installing requirements...
No requirements.
 * Installing platform requirements...
Collecting toga-ios==0.3.0.dev11
  Using cached https://files.pythonhosted.org/packages/36/f1/a5e2f2390b3129768e2399d6c8a2e5ef3ffb2bf82f4e5e33b6bf7842dc7d/toga_iOS-0.3.0.dev11-py3-none-any.whl
Collecting rubicon-objc>=0.3.0 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/ce/55/b7fbfd72cbd3d18322d94305179c6c1805fe4b5e10619d6954adf7f1d6a3/rubicon_objc-0.3.0-py2.py3-none-any.whl
Collecting toga-core==0.3.0.dev11 (from toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/e0/d2/725f505441428638d97cde2eea794a6a328deeec58bfd615fd3a71baa8ad/toga_core-0.3.0.dev11-py3-none-any.whl
Collecting travertino>=0.1.0 (from toga-core==0.3.0.dev11->toga-ios==0.3.0.dev11)
  Using cached https://files.pythonhosted.org/packages/56/3f/f03efe63c2bdc72763ac39777c9ebbab98605ced5c74aefe48b4fa0abb4d/travertino-0.1.2-py3-none-any.whl
Installing collected packages: rubicon-objc, travertino, toga-core, toga-ios
Successfully installed rubicon-objc-0.3.0 toga-core-0.3.0.dev11 toga-ios-0.3.0.dev11 travertino-0.1.2
 * Installing project code...
Processing /Users/jayjay/helloworld
Building wheels for collected packages: helloworld
  Building wheel for helloworld (setup.py) ... done
  Stored in directory: /private/var/folders/f8/zy7rkvp53899hl195sfvcvt40000gp/T/pip-ephem-wheel-cache-cjsjvawa/wheels/b6/bf/df/537ada3f60b669417e3aa1381a3c7178aeb5948c31b14fc2cb
Successfully built helloworld
Installing collected packages: helloworld
Successfully installed helloworld-0.0.1
 * Skipping creation of launch scripts.
 * No icons defined - using default...
 * No splash screen defined...

Installation complete.
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'toga-django==0.3.0.dev11',
  File "/Users/jayjay/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/Users/jayjay/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/jayjay/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/jayjay/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/jayjay/anaconda3/lib/python3.7/site-packages/briefcase/app.py", line 524, in run
    success = self.build_app()
  File "/Users/jayjay/anaconda3/lib/python3.7/site-packages/briefcase/ios.py", line 197, in build_app
    if not self.has_required_xcode_version():
  File "/Users/jayjay/anaconda3/lib/python3.7/site-packages/briefcase/ios.py", line 183, in has_required_xcode_version
    universal_newlines=True
  File "/Users/jayjay/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Users/jayjay/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['xcrun', 'xcodebuild', '-version']' returned non-zero exit status 72.
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
$ xcrun --show-sdk-path
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

**Comment by jay20162016** [comment]
solved using `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
