### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/pybee/briefcase-template.git']' returned non-zero exit status 1 when running beware new

### ISSUE THREAD

**Issue by zurgeg** [beeware/briefcase#249]
I recently created a venv (with  ```virtualenv```) to use beeware. I have followed the instructions and activated the venv. Then I installed beware (```pip install beware```) and run ```beeware new``` and it fails with this error:
```
$ beeware new
Creating new BeeWare project using the Briefcase Template...
>>> cookiecutter https://github.com/pybee/briefcase-template.git

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/cookiecutter", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cookiecutter/cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cookiecutter/main.py", line 63, in cookiecutter
    password=password
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cookiecutter/repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cookiecutter/vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/pybee/briefcase-template.git']' returned non-zero exit status 1.
```
I have running ```pip uninstall briefcase``` and ```pip install briefcase``` but it still happens.
I am running Mac OSX Mojave.

**Comment by zurgeg** [comment]
Fixed by installing Xcode CLI tools.
