### ISSUE TITLE
cookiecutter https://github.com/pybee/briefcase-template is not working as expected

### ISSUE THREAD

**Issue by eerlagu** [beeware/briefcase#279]
Hi, I tried to install Briefcase, 

pip install briefcase and pip install cookiecutter went well, but got this error while getting template.

C:\Users\eerlagu>cookiecutter https://github.com/pybee/briefcase-template
Traceback (most recent call last):
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eerlagu\AppData\Local\Programs\Python\Python37-32\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\cli.py", line 120, in main
    password=os.environ.get('COOKIECUTTER_REPO_PASSWORD')
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\site-packages\cookiecutter\vcs.py", line 99, in clone
    stderr=subprocess.STDOUT,
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "c:\users\eerlagu\appdata\local\programs\python\python37-32\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/pybee/briefcase-template']' returned non-zero exit status 128.

Any help would be appreciated.

**Comment by freakboy3742** [comment]
From the look of the error, you haven't got git installed - or if you do, it's not on your system path. The tutorial (and cookiecutter) assumes that you'll have Git installed, as it's such a ubiquitous tool; if you don't have it installed, the errors get a bit weird.

**Comment by eerlagu** [comment]
C:\Program Files\Git\cmd --> have set up in system path. Appreciate your help.

**Comment by eerlagu** [comment]
Issue is on my side, Im using VPN which validates issuer certificate . since it couldn't find any valid certificates, its getting failed. I tried disabling certificate verification and it worked.

**Comment by freakboy3742** [comment]
Ah - thanks for letting us know. I'll make sure we add that edge case to our testing.
