### ISSUE TITLE
Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.

### ISSUE THREAD

**Issue by devalexandre** [beeware/briefcase#323]
I try make app for IOS but when I run in XCode using iphone 8 with IOS 13,11 display it
2020-03-14 16:38:11.094175-0300 papo de dev[7926:348960] PythonHome is: /Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Python
2020-03-14 16:38:11.101209-0300 papo de dev[7926:348960] PYTHONPATH is: PYTHONPATH=/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app:/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app_packages
2020-03-14 16:38:11.102478-0300 papo de dev[7926:348960] Initializing Python runtime...
2020-03-14 16:38:11.830512-0300 papo de dev[7926:348960] Installing Python NSLog handler...
2020-03-14 16:38:12.580141-0300 papo de dev[7926:348960] Running 'papodedev'...
2020-03-14 16:38:13.009905-0300 papo de dev[7926:348960] Application quit abnormally!
2020-03-14 16:38:13.011635-0300 papo de dev[7926:348960] Traceback (most recent call last):
2020-03-14 16:38:13.013031-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Python/lib/python37.zip/runpy.py", line 193, in _run_module_as_main
2020-03-14 16:38:13.016678-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Python/lib/python37.zip/runpy.py", line 85, in _run_code
2020-03-14 16:38:13.018663-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app/papodedev/__main__.py", line 1, in <module>
2020-03-14 16:38:13.021383-0300 papo de dev[7926:348960]     from papodedev.app import main
2020-03-14 16:38:13.022689-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app/papodedev/app.py", line 5, in <module>
2020-03-14 16:38:13.024517-0300 papo de dev[7926:348960]     from PySide2 import *
2020-03-14 16:38:13.025868-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app_packages/PySide2/__init__.py", line 51, in <module>
2020-03-14 16:38:13.027734-0300 papo de dev[7926:348960]     _setupQtDirectories()
2020-03-14 16:38:13.029009-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app_packages/PySide2/__init__.py", line 21, in _setupQtDirectories
2020-03-14 16:38:13.032563-0300 papo de dev[7926:348960]     import shiboken2
2020-03-14 16:38:13.036403-0300 papo de dev[7926:348960]   File "/Users/alexandre/Library/Developer/CoreSimulator/Devices/F3C9E7B5-45F4-414A-B746-DD64BDB7497E/data/Containers/Bundle/Application/B06E8B00-BCDB-473D-BFDD-114D4AEB2939/papo de dev.app/Library/Application Support/com.example.papodedev/app_packages/shiboken2/__init__.py", line 27, in <module>
2020-03-14 16:38:13.039139-0300 papo de dev[7926:348960]     from .shiboken2 import *
2020-03-14 16:38:13.041489-0300 papo de dev[7926:348960] ModuleNotFoundError: No module named 'shiboken2.shiboken2'
2020-03-14 16:38:13.172871-0300 papo de dev[7926:348960] *** Assertion failure in void _UIApplicationMainPreparations(int, char **, NSString *__strong, NSString *__strong)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3901.4.2/UIApplication.m:4715
2020-03-14 16:38:13.174444-0300 papo de dev[7926:348960] Python runtime error: Unable to instantiate the UIApplication delegate instance. No class named PythonAppDelegate is loaded.

**Comment by devalexandre** [comment]
I`m using pyside2 and not have documetation , about PythonAppDelegate some example

**Comment by devalexandre** [comment]
How Bug

```
briefcase new
using pyside2
briefcase create IOS
briefcase run iOS -d "iPhone 11"
```

**Comment by freakboy3742** [comment]
PySide2 isn't a supported configuration on mobile platforms, because PySide2 isn't supported on mobile.

The new project template offers PySide2 support so that Briefcase can be used for desktop platforms, where PySide2 *does* have support.

The only widget toolkit that is currently supported on mobile platforms is Toga. In theory, it should be possible for Briefcase to support Kivy, but no work has been done to support that configuration.

**Comment by devalexandre** [comment]
thanks, I go test toga
