### ISSUE TITLE
Fails if dependencies include .pth files

### ISSUE THREAD

**Issue by tmontes** [beeware/briefcase#381]
# Context

As a [Mu Editor](https://github.com/mu-editor/mu) contributor, and having worked a bit on improving its packaging, I joined the sprint today in order to understand how easy/difficult it will be for Mu to be packaged with the newer `briefcase` 0.3 release.

Facts about Mu packaging:
* macOS Application Bundle produced with `briefcase` 0.2.x.
* Windows installer produced with `pynsist`.
* PyPI wheel produced with `wheel` + `setuptools`.
* Also included in Debian, Ubuntu, and Raspbian package repositories. Maybe Fedora, too. Not 100% sure because Linux distribution packaging has been, AFAICT, handled outside of the development tree (or maybe it hasn't had much love, in the last 12 months or so).

Challenges about Mu packaging:
* Having a single source of truth WRT to dependency specification and meta data.
* The current solution is `setuptools` based and all of the information sourced from `setup.py` + `setup.cfg` (from there, we use a non-trivial script to produce the necessary `pynsist` input such that it can do its thing, on Windows).

# The Issue

Packaging Mu on Windows leads to a partially ok Mu installation for various motives. In this issue, I'm focusing on a failure that results when trying to bring up its Python REPL -- it  leads to a crash (Mu's fault) because a particular module fails to import, resulting in an unhandled exception.

Specifics:
* Mu's REPL is based on `qtconsole` that, on Windows, ends up requiring `pywin32`.
* `pywin32` uses `.pth` files to *guide* `site.py` in populating `sys.path` in a specific way.

Bottom line:
* Briefcase packaged Windows applications that depend on `pywin32` fail to import `win32api`, on of its modules.

# Investigation

After a few hints from @freakboy3742 and @dgelessus at Gitter, here's what's going on:

* The Python support package being used is the default one: one of the "embeddable zip file" packages from https://www.python.org/downloads/windows/. (FTR, all if this was explored with Python 3.6.8 64 bit).
* In particular it includes a `pythonXX._pth` that:
  * Makes Python run in [isolated mode](https://docs.python.org/3/using/cmdline.html#interface-options)...
  * ...and prevents [site.py](https://docs.python.org/3/library/site.html) from being loaded...
  * ...per [these docs here](https://docs.python.org/3/using/windows.html#finding-modules).
* Such `pythonXX._pth` file is actually overwritten by `briefcase` in order to:
  * Add the `src\app` and `src\app_packages` to `sys.path` such that both the application and its dependencies can be successfully imported.
* However, the presence of the `._pth` file:
  * Prevents the `site` module from being loaded at startup...
  * ...which would be responsible for populating `sys.path` from any `.pth` files that are found on the `site-packages` directories.

# A Successful Hack

With this information, I invested some time fiddling with these things to see if, at least, I could make it work. Here's what I did that resulted in a working Mu REPL (thus, its underlying `import win32api` working!):

* Hacked the cookiecutter template's `briefcase.toml` file (took me quite figuring out where this file was coming from!!!):
  * Set `app_packages_path` to `src\python\lib\site-packages`, instead.
* Then, hacked `briefcase`'s overwriting of `pythonXX._pth` to produce:

  ```
  pythonXX.zip
  .
  lib\site-packages
  import site
  ..\app
  ```
  * This lets Python find the Standard Library with the first 2 lines...
  * ...find application dependencies with the 3rd line...
  * ...has `site` imported such that `.pth` files in the application dependencies are handled...
  * ...lastly adds the application package path such that it can be imported and run.
* Lastly, I observed that having `site` imported lead to an over-populated, non-safe `sys.path`. For some reason, my local Python installation's `site-packages` was being added, and then maybe some more.
* With that, the last step of the hack, was creating a `sitecustomize.py`, which is automatically picked up when `site` is imported per the revamped `pythonXX._pth`. Here's my take:
  ```
  import re
  import sys

  _IS_LOCAL = re.compile(r'(src\\python|src\\app)', re.IGNORECASE)

  sys.path = [path for path in sys.path if _IS_LOCAL.search(path)]
  ```

With these three changes, the `import win32api` in Mu succeeds and, ultimately Mu works as intended WRT to providing a Python REPL.

# Thoughts

* Handling `.pth` files in dependencies is a must, I'd venture saying.
* My approach is the result of fiddling and exploring and I don't like it very much (but it works!). It feels unnecessarily complicated and, thus, brittle.
* Somewhat orthogonal, but related, maybe having a `venv` to which dependencies are `pip install`ed instead of `pip install --target`ed will be more robust, at least for the platforms where that is feasible. No worries about playing with import PATHs in three distinct places (well, maybe some PATH cleaning up could be in order, to guarantee isolation -- see my `sitecustomize.py`, above).

All in all, I leave this issue here in the hope that some useful discussion comes out of it, while serving as a hack-guide to someone facing a similar failures. I'm not sure yet about what could be a solid, sustainable, simple, future-proof solution.

Shall we discuss? :)

PS: I suppose similar failures will happen on any platform, as long as `.pth` files are brought in by dependencies.

**Comment by tmontes** [comment]
**NOTE**: The `sitecustomize.py` I pasted in the previous comment is too aggressive. Realized that after the fact. Will come back a paste something that works *and* excludes non application/dependecy/bundled standard library paths.

**Comment by freakboy3742** [comment]
Thanks for the thorough investigation and writeup! 

For background: `app_packages` was introduced because it allowed us to isolate the support package from the dependencies. That's not a huge concern for "normal" Python installs because the Python interpreter is installed once and packages are installed into that interpreter (or a virtual environment); but in an app packaging world, updating the support package is something you're more likely to want to do independent of dependencies. I'm not *fundamentally* opposed to breaking this separation and using site_packages; but it's worth being aware what the consequence of that decision would be.

That said - the remaining fixes all seem like (a) a good set of changes, and (b) not fundamentally incompatible with using a separate `app_packages` folder - we just need to add `app_packages` to the `python3.X._pth` file.

The fact that your local Python's path is being added to sys.path is definitely odd - and definitely something we want to avoid; the site path filtering seems like an interesting approach, although I guess the real fix is to work out why the extra path elements are leaking into `sys.path` in the first place.

Ideally, these changes wouldn't be something baked into the Briefcase sources either - they'd be something included in [the briefcase template](https://github.com/beeware/briefcase-windows-msi-template/) so that an end-user can easily customize the contents.

**Comment by tmontes** [comment]
Thanks for the feedback.

> That said - the remaining fixes all seem like (a) a good set of changes, and (b) not fundamentally incompatible with using a separate `app_packages` folder - we just need to add `app_packages` to the `python3.X._pth` file.

It's already there, in the current `master`! But that isn't enough, apparently. My understanding:
* The `._pth` file prevents `site` from being imported (unless it explicitly imports it).
* But `site` runs the code that processes the regular `.pth` files in `site-packages`.

> The fact that your local Python's path is being added to sys.path is definitely odd - and definitely something we want to avoid; the site path filtering seems like an interesting approach, although I guess the real fix is to work out why the extra path elements are leaking into `sys.path` in the first place.

Yet to clarify if this.
* Is it because `site` is being explictly brought in, in my hacked `._pth` file?
* How is `sys.path` different if no `._pth` file is ever there?

> Ideally, these changes wouldn't be something baked into the Briefcase sources either - they'd be something included in [the briefcase template](https://github.com/beeware/briefcase-windows-msi-template/) so that an end-user can easily customize the contents.

Understood and generally agreed (even though, as a side comment, I'd like to have `briefcase` embed/bundle the "default" templates itself, such that it can be used completely offline -- a whole different topic and subsequent discussion). :)

I will investigate further and share my findings.

**Comment by tmontes** [comment]
# Investigation

Environment:
* Windows 10 + www.python.org's 64 bit Python 3.6 installed for current user at `C:\Users\test\AppData\Local\Programs\Python\Python36>`.
* Working with current Mu Editor and `briefcase` master.
* Created a minimal `pyproject.toml` file.
* Repository root at `C:\Users\test\work\github.com\mu`.
* Working with hacked `briefcase-windows-msi-template` that produces per-user MSI installers (see #382).

Objective:
* Must be able to import `PyQt5` and `win32api`.
* `sys.path` must not include PATHs outside of the application directory.

## Starting Point: current `master`

### Package Source Observations

(after running `briefcase package`)

```
C:\Users\test\work\github.com\mu>"windows\Mu Editor\src\python\python.exe" -q
>>> import sys
>>> print(*map(repr, sys.path), sep='\n')
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\python\\python36.zip'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\python'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\\\app'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\\\app_packages'

>>> import PyQt5
>>> PyQt5
<module 'PyQt5' from 'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\\\app_packages\\PyQt5\\__init__.py'>

>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

Summary:
* `sys.path` looks good.
* Imports `PyQt5` from the right source.
* Fails at importing `win32api`.


### User-Installed Package Observations

(after installing MSI package)

```
C:\Users\test>"AppData\Local\Programs\Mu Editor\python\python.exe" -q
>>> import sys
>>> print(*map(repr, sys.path), sep='\n')
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\python\\python36.zip'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\python'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\\\app'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\\\app_packages'
>>>
>>> import PyQt5
>>> PyQt5
<module 'PyQt5' from 'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\\\app_packages\\PyQt5\\__init__.py'>
>>>
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

Summary:
* `sys.path` looks good.
* Imports `PyQt5` from the right source.
* Fails at importing `win32api`.


## Where to, next?

Facts:
* The `site` module processes `.pth` files (used by `pywin32` to provide `win32api`, here).
* The presence of `python36._pth` prevents `site` from being auto-imported.

Options:
1. Add `import site` to `python36._pth`.
2. Drop the `python36._pth`.

If we go with 2., a way of adding `src\app` and `src\app_packages` to `sys.path` must be put in place. Options:
* Create a `sitecustomize.py` that adds them to the PATH.
* Add a `.pth` file in `src\python\lib\site-packages` pointing to them.

## Option 1 - Add `import site` to `python36._pth`

Contents of hacked `python36._pth` after the change:
```
python36.zip
.
..\\app
..\\app_packages
import site
```

### Package Source Observations

(after running `briefcase package`)

```
C:\Users\test\work\github.com\mu>"windows\Mu Editor\src\python\python.exe" -q
>>> import sys
>>> print(*map(repr, sys.path), sep='\n')
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\python\\python36.zip'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\python'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\app'
'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\app_packages'
'C:\\Users\\test\\AppData\\Roaming\\Python\\Python36\\site-packages'
>>>
>>> import PyQt5
>>> PyQt5
<module 'PyQt5' from 'C:\\Users\\test\\work\\github.com\\mu\\windows\\Mu Editor\\src\\app_packages\\PyQt5\\__init__.py'>
>>>
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

Summary:
* `sys.path` now includes a foreign PATH.
* Imports `PyQt5` from the right source.
* Fails at importing `win32api`.

### User-Installed Package Observations

(after installing MSI package)

```
C:\Users\test>"AppData\Local\Programs\Mu Editor\python\python.exe" -q
>>> import sys
>>> print(*map(repr, sys.path), sep='\n')
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\python\\python36.zip'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\python'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\app'
'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\app_packages'
'C:\\Users\\test\\AppData\\Roaming\\Python\\Python36\\site-packages'
>>>
>>> import PyQt5
>>> PyQt5
<module 'PyQt5' from 'C:\\Users\\test\\AppData\\Local\\Programs\\Mu Editor\\app_packages\\PyQt5\\__init__.py'>
>>>
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32api'
```

Summary:
* `sys.path` now includes a foreign PATH.
* Imports `PyQt5` from the right source.
* Fails at importing `win32api`.

### Add `import site` to `python36._pth` summary

Positive:
* Nothing.

Negative:
* `sys.path` now polluted.

Wondering:
* For some reason, importing `site`, did not process the `.pth` files in `src\app_packages`.


(will comment now, to "commit" this to github, and continue in follow-up edits)

**Comment by tmontes** [comment]
# Stop and Think

From the experiments above, as soon as `site` is auto-imported -- either by explicitly adding it to `python36._pth`, or by droping that file completely -- `sys.path` becomes polluted with non-local PATHs.

Explanation:
* `site` does when it finds a user base and `site-packages` by looking at the result of `sysconfig.get_config_var('userbase')` and `sysconfig.get_path('purelib', 'nt_user')` - see code in [`site.py`:`getuserbase`](https://github.com/python/cpython/blob/3.6/Lib/site.py#L237) and [`site.py`:`getusersitepackages`](https://github.com/python/cpython/blob/3.6/Lib/site.py#L251).

**Comment by wwj718** [comment]
Hi @tmontes  , I run the steps you mentioned （A Successful Hack） but still can't import win32api, the error is 

```
import win32api
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by monzelr** [comment]
I had the same issue with packaging pywin32 in Briefcase and as @tmontes figured it out correctly, `*.pth` files are **correctly packed** by Briefcase, but the **link** to those `*.pth`-files is **wrong**.

The python package `site` and its variable `site.USER_SITE` points to a incorrect path (for me it was `C:\\Users\\RuneMonzel\\AppData\\Roaming\\Python\\Python38\\site-packages`) and thus all `.pth` in the `app_packages` folder will not be loaded correctly. However, python's documentation says you can modify the import behaviour with the `site` package: https://docs.python.org/3/library/site.html

This fix should be applied if any module does extra imports via a `.pth` file, which is normally located in `site-packages` (or when using Briefcase in `app_packages`).
A fast fix:


```python
try:
    import win32con, win32event, win32process
    from win32com.shell.shell import ShellExecuteEx
    from win32com.shell import shellcon
    
except ModuleNotFoundError:
    print("Try to find 'app_packages' folder and to add this to python's 'site' package.")
    app_packages = ""
    for path in sys.path:
        if path.endswith("app_packages"):
            app_packages = path
    if app_packages == "":
        raise ModuleNotFoundError
    else:
        
        import site
        site.USER_SITE = app_packages  # correct the 'site-packages' path to 'app_packages' path
        site.main()  # recall site package thus all .pth in 'app_packages' will be called
        
        import win32con, win32event, win32process
        from win32com.shell.shell import ShellExecuteEx
        from win32com.shell import shellcon
        
    for path in sys.path:
        print(path)
```

The output of the code above shows, that `sys.path` is now extended with the paths found in `pywin32.pth`:
```
Try to find 'app_packages' folder and to add this to python's 'site' package.
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\python\python38.zip
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\python
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\app
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\app_packages
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\app_packages\win32
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\app_packages\win32\lib
C:\Users\RuneMonzel\AppData\Local\Programs\AutoLucid\app_packages\Pythonwin
```


@freakboy3742 :
I am wondering if it is possible to change the `site.USER_SITE` variable to the folder `app_packages` in the standard cookie-cutter template? Thus all python modules with `.pth` dependencies would be imported normally.
One way would be importing an extra module in `pythonXX._pth`, like `import sitecustomize` which calls this kind of code:
```python
import sys
import site
app_packages = ""
for path in sys.path:
    if path.endswith("app_packages"):
        app_packages = path
if app_packages != "":
    site.USER_SITE = app_packages  # correct the 'site-packages' path to 'app_packages' path
    site.main()  # recall site package thus all .pth in 'app_packages' will be called
```

**Comment by freakboy3742** [comment]
@monzelr Thanks for the extra detail. I think this may be tracking the same problem as #669; and yes - this is absolutely something that should be fixed. The general approach you've described makes sense; we'll need to find a good place to drop a sitecustomize script so it is picked up on all platforms.

**Comment by freakboy3742** [comment]
#669 has a more direct test/manifestation of this; while the report here is windows specific, it's likely `USER_SITE` problems exist on every platform.
