### ISSUE TITLE
ImportError: libffi.so.6: with AppImage build on Ubuntu 16.04

### ISSUE THREAD

**Issue by Maradonna90** [beeware/briefcase#427]
This might be related to #420 
I used Python 3.7 and did the helloworld-tutorial for linux. I used Github Actions with Ubuntu 16.04 and Python 3.7 to build and package the app in order to execute it on my Arch Linux machine.

Full Error:
```Traceback (most recent call last):
  File "/tmp/.mount_Hello_GD9gw9/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_Hello_GD9gw9/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_Hello_GD9gw9/usr/app/helloworld/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_Hello_GD9gw9/usr/app/helloworld/app.py", line 27, in main
    return HelloWorld()
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/toga/app.py", line 208, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/toga/platform.py", line 39, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/toga_gtk/app.py", line 8, in <module>
    import gbulb
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/gbulb/__init__.py", line 1, in <module>
    from .glib_events import *
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/gbulb/glib_events.py", line 12, in <module>
    from gi.repository import GLib, Gio
  File "/tmp/.mount_Hello_GD9gw9/usr/app_packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: libffi.so.6: cannot open shared object file: No such file or directory


```
I build the whole Image with the `--no-docker` option since the azure docker version is failing a docker version text.

Github Workflow: https://github.com/Maradonna90/beeware-tutorial/blob/master/.github/workflows/linux.yml

I uploaded the AppImage under Releases: https://github.com/Maradonna90/beeware-tutorial/releases

**Comment by Maradonna90** [comment]
Ok Arch Linux uses a newer libffi version (libffi.so.6), but the aur provides a package with `yay -S libffi6`

**Comment by freakboy3742** [comment]
I think that this is the same issue as #420; however, you *shouldn't* need to install an extra libffi version to get the AppImage to work. The AppImage *should* be fully self contained. If it isn't (and it clearly isn't in this case), that's a bug.
