### ISSUE TITLE
import ssl error

### ISSUE THREAD

**Issue by jamesabel** [beeware/briefcase#46]
When executing:
    import ssl
I get:

Traceback (most recent call last):
  File "/Users/james/projects/pycon_projects/hello_briefcase/hello_briefcase/macOS/hello_briefcase.app/Contents/Resources/python/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/james/projects/pycon_projects/hello_briefcase/hello_briefcase/macOS/hello_briefcase.app/Contents/Resources/python/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/james/projects/pycon_projects/hello_briefcase/hello_briefcase/macOS/hello_briefcase.app/Contents/Resources/app/hello_briefcase/__main__.py", line 1, in <module>
    from hello_briefcase.app import main
  File "/Users/james/projects/pycon_projects/hello_briefcase/hello_briefcase/macOS/hello_briefcase.app/Contents/Resources/app/hello_briefcase/app.py", line 10, in <module>
    import ssl
  File "/Users/james/projects/pycon_projects/hello_briefcase/hello_briefcase/macOS/hello_briefcase.app/Contents/Resources/python/lib/python3.5/ssl.py", line 99, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'

**Comment by freakboy3742** [comment]
It appears that the most recent builds don't have the binary modules included; need to dig into the build process to work out why.

**Comment by inJeans** [comment]
I believe I am having a similar problem trying to `import keras` in my app. I just wanted to confirm that briefcase should be packaging import modules into binaries? Or does it only include modules that come with the standard lib?

**Comment by freakboy3742** [comment]
I believe this has been addressed in recent support package builds.

**Comment by jgirardet** [comment]
Hi,
latest briecase.
just add `import ssl" to the default app
Following error :
```
[mycartable] Built linux/MyCartable-0.0.1-x86_64.AppImage

[mycartable] Starting app...

Traceback (most recent call last):
  File "/tmp/.mount_MyCarthLt0Ty/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_MyCarthLt0Ty/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_MyCarthLt0Ty/usr/app/mycartable/__main__.py", line 2, in <module>
    import ssl
  File "/tmp/.mount_MyCarthLt0Ty/usr/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
Jimmy
