### ISSUE TITLE
iOS error - ValueError: Library 'c' not found

### ISSUE THREAD

**Issue by davidferguson** [beeware/briefcase#48]
When following the tutorials, I am able to complete tutorial 1, but tutorial 2 will not run on a physical iOS device - only on the simulator.

When I attempt to run it on an actual iOS device, the app will display the splash screen but then quit straight after.

The error message from the console is:
```2017-05-26 14:00:53.570 Tutorial 0[11917:5779110] PythonHome is: /var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Python.framework/Resources
2017-05-26 14:00:53.583 Tutorial 0[11917:5779110] PYTHONPATH is: PYTHONPATH=/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app:/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages
2017-05-26 14:00:53.584 Tutorial 0[11917:5779110] Initializing Python runtime
2017-05-26 14:00:54.830 Tutorial 0[11917:5779110] Running /var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/__main__.py
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/__main__.py", line 1, in <module>
    from tutorial_0.app import main
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app/tutorial_0/app.py", line 1, in <module>
    import toga
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga/__init__.py", line 114, in <module>
    set_platform()
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga/__init__.py", line 86, in set_platform
    local_vars['platform'] = importlib.import_module(module_name)
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Python.framework/Resources/lib/python35.zip/importlib/__init__.py", line 126, in import_module
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga_iOS/__init__.py", line 2, in <module>
    from .app import *
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/toga_iOS/app.py", line 1, in <module>
    from rubicon.objc import objc_method
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/__init__.py", line 3, in <module>
    from .objc import (
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/objc.py", line 27, in <module>
    c = cdll.LoadLibrary(_find_or_error('c'))
  File "/var/containers/Bundle/Application/C6D15E50-4F2F-41B3-9CEE-CF09CF1D4637/Tutorial 0.app/Library/Application Support/org.pibakery.tutorial_0/app_packages/rubicon/objc/objc.py", line 23, in _find_or_error
    raise ValueError("Library {!r} not found".format(name))
ValueError: Library 'c' not found
2017-05-26 14:00:58.937 Tutorial 0[11917:5779110] Application quit abnormally!
2017-05-26 14:00:59.029 Tutorial 0[11917:5779110] Leaving
```

I'm using Xcode 7.3.1.

Any advice?

**Comment by freakboy3742** [comment]
Thanks for the report; I'll have to dig into this and work out what is going on.

**Comment by tleeuwenburg** [comment]
I'm experiencing the same thing, XCode 8.3.3.

**Comment by cculianu** [comment]
This doesn't happen to me.  It works perfectly for me.

FWIW I'm on Xcode 9.4. 

Is this still an issue for you guys on newish Xcode?

**Comment by freakboy3742** [comment]
Looks like this may have been a problem with a specific support build.
