### ISSUE TITLE
Keep getting "cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed." with "briefcase create"

### ISSUE THREAD

**Issue by Sl-L** [beeware/briefcase#499]
**Description**
I keep getting this error while try to use "briefcase create" command to package my program:
```
(beeware_tutorial) C:\Users\esteb\Desktop\beeware_tutorial\helloworld>briefcase create

[helloworld] Generating application template...
Using app template: https://github.com/beeware/briefcase-windows-msi-template.git
Assigning helloworld an application GUID of 93bbf2ae-12d0-580c-aeb0-965dc4c04b69
Traceback (most recent call last):
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\esteb\Desktop\beeware_tutorial\Scripts\briefcase.exe\__main__.py", line 7, in <module>
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\briefcase\__main__.py", line 11, in main
    command(**options)
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\briefcase\commands\create.py", line 684, in __call__
    state = self.create_app(app, **full_options(state, options))
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\briefcase\commands\create.py", line 635, in create_app
    self.generate_app_template(app=app)
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\briefcase\commands\create.py", line 288, in generate_app_template
    self.cookiecutter(
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\cookiecutter\main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\cookiecutter\repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "c:\users\esteb\desktop\beeware_tutorial\lib\site-packages\cookiecutter\vcs.py", line 84, in clone
    raise VCSNotInstalled(msg)
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.
```
And yes, i have git installed and can use it in cmd and in bash.

**To Reproduce**
I just follow, step-by-step, the beeware tutorial.

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8.5
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0.dev23
   - Git: 2.28.0.windows.1

**Extra Notes**
- I have also tried without using a virtual environment, and nothing has changed.

**Comment by freakboy3742** [comment]
Thanks for the report. This is a very unusual edge case - Briefcase's check that git is installed is passing; but cookiecutter's check is failing.

Can I ask for some additional debugging details:

 1. What version of cookiecutter is installed (`pip freeze` can tell you this)

 2. From a command prompt, what happens when you run `cookiecutter https://github.com/beeware/briefcase-windows-msi-template.git`?

 3. From a Python prompt (inside the briefcase venv), what output do you get from running:

    from cookiecutter import vcs
    vcs.is_vcs_installed('git')

**Comment by Sl-L** [comment]
1: cookiecutter-1.7.2
2:
```
Traceback (most recent call last):
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\esteb\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\esteb\Desktop\BeeWare_Tutorial\venv\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\cookiecutter\cli.py", line 140, in main
    cookiecutter(
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\cookiecutter\main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\cookiecutter\repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "c:\users\esteb\desktop\beeware_tutorial\venv\lib\site-packages\cookiecutter\vcs.py", line 84, in clone
    raise VCSNotInstalled(msg)
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.
```
3: False

Extra, than make this strange:
-Run `git` has as response the usual:
```
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisions)
   bisect            Use binary search to find the commit that introduced a bug
   diff              Show changes between commits, commit and working tree, etc
   grep              Print lines matching a pattern
   log               Show commit logs
   show              Show various types of objects
   status            Show the working tree status

grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   tag               Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch             Download objects and refs from another repository
   pull              Fetch from and integrate with another repository or a local branch
   push              Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
```
- I also try installing git with chocolatey
- Git, even before installing another with `choco install git`, is in %PATH%

**Comment by freakboy3742** [comment]
Ok - next test: What is the output of:
```
from shutil import which
which('git')
````

**Comment by Sl-L** [comment]
Also False, I guess, cuz' don't return nothing.

**Comment by freakboy3742** [comment]
Ok - so `shutil.which()` is a Python builtin; the return value of `None` is asserting that `git` isn't on your PATH. I have no idea why that would be, though. It might be worth checking `os.environ['PATH']` to see if it matches the value you're expecting.

There's not much Briefcase can do in this case - *our* git check is passing; we're relying on Cookiecutter, which is itself relying on the Python standard library.

**Comment by Sl-L** [comment]
Another strange thing is:
```
>>> import os
>>> path = os.environ['PATH']
>>> "Git" in path
True
>>>
```

**Comment by Sl-L** [comment]
I figured out what was happening, it was caused by shutil.which being confusing by the last semicolon of the PATHEXT.
Here is better explained: https://stackoverflow.com/questions/56399696/shutil-which-not-finding-programs-without-appending-file-extension
