### ISSUE TITLE
ValueError when executing `briefcase run` with specific device (`-d`) for iOS

### ISSUE THREAD

**Issue by The-Judge** [beeware/briefcase#528]
**Describe the bug**
When launching `briefcase run iOS -d "iPhone 11"` (as suggested in https://docs.beeware.org/en/latest/tutorial/tutorial-5/iOS.html), the following happens:

```
$ briefcase run iOS -d "iPhone 11"

[helloworld] Generating application template...
Using app template: https://github.com/beeware/briefcase-iOS-Xcode-template.git
Using existing template (sha 185a566d3a5829784d5fd5b3e0273573b3d29de4, updated Sun Jun 21 12:41:13 2020)

[helloworld] Installing support package...
Using support package https://briefcase-support.org/python?platform=iOS&version=3.8
... using most recent revision
Python-3.8-iOS-support.b3.tar.gz already downloaded
Unpacking support package...

[helloworld] Installing dependencies...
Collecting toga-iOS>=0.3.0.dev20
  Using cached toga_iOS-0.3.0.dev25-py3-none-any.whl (34 kB)
Collecting toga-core==0.3.0.dev25
  Using cached toga_core-0.3.0.dev25-py3-none-any.whl (484 kB)
Collecting rubicon-objc>=0.3.0
  Using cached rubicon_objc-0.4.0-py3-none-any.whl (53 kB)
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Installing collected packages: travertino, toga-core, rubicon-objc, toga-iOS
Successfully installed rubicon-objc-0.4.0 toga-core-0.3.0.dev25 toga-iOS-0.3.0.dev25 travertino-0.1.3

[helloworld] Installing application code...
Installing src/helloworld...

[helloworld] Installing application resources...
Unable to find src/helloworld/resources/helloworld-20.png for 20px application icon; using default
Unable to find src/helloworld/resources/helloworld-29.png for 29px application icon; using default
Unable to find src/helloworld/resources/helloworld-40.png for 40px application icon; using default
Unable to find src/helloworld/resources/helloworld-58.png for 58px application icon; using default
Unable to find src/helloworld/resources/helloworld-60.png for 60px application icon; using default
Unable to find src/helloworld/resources/helloworld-76.png for 76px application icon; using default
Unable to find src/helloworld/resources/helloworld-80.png for 80px application icon; using default
Unable to find src/helloworld/resources/helloworld-87.png for 87px application icon; using default
Unable to find src/helloworld/resources/helloworld-120.png for 120px application icon; using default
Unable to find src/helloworld/resources/helloworld-152.png for 152px application icon; using default
Unable to find src/helloworld/resources/helloworld-167.png for 167px application icon; using default
Unable to find src/helloworld/resources/helloworld-180.png for 180px application icon; using default
Unable to find src/helloworld/resources/helloworld-1024.png for 1024px application icon; using default

[helloworld] Created iOS/Hello World
Traceback (most recent call last):
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/platforms/iOS/xcode.py", line 86, in select_target_device
    udid = str(UUID(udid_or_device)).upper()
  File "/Users/marcrichter/.pyenv/versions/3.8.6/lib/python3.8/uuid.py", line 171, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/__main__.py", line 11, in main
    command(**options)
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/commands/run.py", line 68, in __call__
    state = self.build_command(app, **full_options(state, options))
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/commands/build.py", line 63, in __call__
    state = self._build_app(app, update=update, **options)
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/commands/build.py", line 44, in _build_app
    state = self.build_app(app, **full_options(state, options))
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/platforms/iOS/xcode.py", line 218, in build_app
    udid, iOS_version, device = self.select_target_device(udid)
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/platforms/iOS/xcode.py", line 129, in select_target_device
    for iOS_version, devices in sorted(
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/platforms/iOS/xcode.py", line 131, in <lambda>
    key=lambda item: tuple(int(v) for v in item[0].split('.')),
  File "/Users/marcrichter/.local/share/virtualenvs/beeware_tutorial--0oC6Si6/lib/python3.8/site-packages/briefcase/platforms/iOS/xcode.py", line 131, in <genexpr>
    key=lambda item: tuple(int(v) for v in item[0].split('.')),
ValueError: invalid literal for int() with base 10: 'iOS 14'
```

When executing `briefcase run iOS` without `-d` and select "iPhone 11" (Selection 6), the emulator starts and copies the app.

**To Reproduce**
1. Follow the Beeware Tutorial at https://docs.beeware.org/en/latest/tutorial/tutorial-0.html until "[Tutorial 5 - Taking it Mobile](https://docs.beeware.org/en/latest/tutorial/tutorial-5/index.html)" and fill all the examples listed so far.
2. Select the iOS path.
3. When one should trigger the `briefcase run iOS` task, execute it as the variant `briefcase run iOS -d "iPhone 11"`

**Expected behavior**
The same behavior as with `briefcase run iOS` + manual selection of "iPhone 11".

**Environment:**
 - Operating System: MacOSX 11.0.1
 - Python version: 3.8.6
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0.dev25

**Comment by freakboy3742** [comment]
Apologies for the late response; unfortunately, I suspect the window of opportunity for investigating this has probably passed.

However, on the off chance you're still able to reproduce it - could I get you to provide the output of `xcrun simctl list -j`? This is the output that Briefcase will be parsing to determine which simulators are available; the error you're reporting suggests there's an issue mapping the name of the device to the UUID that represents that device.

**Comment by ChillarAnand** [comment]
I stumbled on this error while setting up a new project. 

`get_simulators` is returning `OS Version` and it is being used as a key for sorting. We can just split it and use the version number for sorting.
