### ISSUE TITLE
Beeware Briefcase dev ERROR: pythonnet

### ISSUE THREAD

**Issue by varun-hemanth** [beeware/briefcase#563]
Newbie here!

I have been following the tutorial document to create my very first Beeware app.

My Beeware got installed successfully. 

I also set up the virtual environment from section 1.3, page 5, successfully. I sucessfully installed the Beeware tools, briefcase.

The command briefcase new worked fine and I got all the prompts thereafter as mentioned in the tutorial document until I reached section 2.3.

I typed in cd helloworld2.

That worked fine.

BUT, after this step, when I key in:
briefcase dev i.e,

(beeware-venv) C:\...>cd helloworld2
(beeware-venv) C:\...>briefcase dev

This is where the problem arises. I get a series of errors to this effect:

**[helloworld2] Installing dependencies...
Collecting toga-winforms>=0.3.0.dev20
  Using cached toga_winforms-0.3.0.dev26-py3-none-any.whl (37 kB)
Requirement already satisfied: toga-core==0.3.0.dev26 in c:\users\name\beeware-tutorial\beeware-venv\lib\site-packages (from toga-winforms>=0.3.0.dev20) (0.3.0.dev26)
Collecting pythonnet
  Using cached pythonnet-2.5.1.tar.gz (1.9 MB)
Requirement already satisfied: travertino>=0.1.3 in c:\users\name\beeware-tutorial\beeware-venv\lib\site-packages (from toga-core==0.3.0.dev26->toga-winforms>=0.3.0.dev20) (0.1.3)
Requirement already satisfied: pycparser in c:\users\name\beeware-tutorial\beeware-venv\lib\site-packages (from pythonnet->toga-winforms>=0.3.0.dev20) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\name\beeware-tutorial\beeware-venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"'; __file__='"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\name\AppData\Local\Temp\pip-wheel-q1km3kpl'
       cwd: C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\
  Complete output (86 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.8.1.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '16.7.0.37604' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'.
  Restoring NuGet package NUnit.3.12.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\packages'**

  NuGet Config files used:
      C:\Users\name\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\name\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  Traceback (most recent call last):
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\tools\geninterop\geninterop.py", line 307, in <module>
      sys.exit(main())
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\tools\geninterop\geninterop.py", line 287, in main
      python_h = preprocess_python_headers()
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\tools\geninterop\geninterop.py", line 207, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\setup.py", line 630, in <module>
      setup(
    File "c:\users\name\beeware-tutorial\beeware-venv\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\users\name\beeware-tutorial\beeware-venv\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\setup.py", line 302, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\users\\name\\beeware-tutorial\\beeware-venv\\scripts\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop39.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet, toga-winforms
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\name\beeware-tutorial\beeware-venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"'; __file__='"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\name\AppData\Local\Temp\pip-record-n01ligg3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\name\beeware-tutorial\beeware-venv\include\site\python3.9\pythonnet'
         cwd: C:\Users\name\AppData\Local\Temp\pip-install-e31napox\pythonnet_055b59845f9a4a06b00668ed7eeca097\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\name\beeware-tutorial\beeware-venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"'; __file__='"'"'C:\\Users\\name\\AppData\\Local\\Temp\\pip-install-e31napox\\pythonnet_055b59845f9a4a06b00668ed7eeca097\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\name\AppData\Local\Temp\pip-record-n01ligg3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\name\beeware-tutorial\beeware-venv\include\site\python3.9\pythonnet' Check the logs for full command output.
Unable to install dependencies. This may be because one of your dependencies is invalid, or because pip was unable to connect to the PyPI server.

Can anyone explain what's going wrong here?

**Comment by freakboy3742** [comment]
Hi @varun-hemanth - The problem is that you're using Python 3.9 on Windows. On Windows, Toga uses the pythonnet library to access the Windows native system libraries; however, Pythonnet hasn't been updated to support Python 3.9. Unfortunately, python net is an external project, and I don't have any visibility on when they plan to publish an official Python 3.9 version.

This problem is mentioned in the tutorial (Possible errors during installation, under the Windows tab on Tutorial step 1). Admittedly, the error message is slightly different on Python 3.9, but it does mention Python.net as the source of the problem.

**Comment by varun-hemanth** [comment]
@freakboy3742 Thank you so much for your response.

**Comment by abirshandilya07** [comment]
that was very helpful for me too thx

**Comment by Mahembajr** [comment]
i faced the same error, any idea what i should do next

**Comment by Mahembajr** [comment]
apt-get install sox ffmpeg libcairo2 libcairo2-dev
apt-get install texlive-full
pip3 install manimlib
apt install libpython3.9-dev


i tried to install those and it was solved
