### ISSUE TITLE
Update wizard to improve errors with special characters

### ISSUE THREAD

**Issue by Viridescence** [beeware/briefcase#580]
**Describe the bug**
At the

**To Reproduce**
1. run `briefcase new` normally
2. Type a special character like © or ∞ as the formal name
3. See error

`Formal Name [Hello World]: ∞
Traceback (most recent call last):
  File "/Users/user/venv/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/Users/user/venv/lib/python3.7/site-packages/briefcase/__main__.py", line 11, in main
    command(**options)
  File "/Users/user/venv/lib/python3.7/site-packages/briefcase/commands/new.py", line 523, in __call__
    state = self.new_app(template=template, **options)
  File "/Users/user/venv/lib/python3.7/site-packages/briefcase/commands/new.py", line 461, in new_app
    context = self.build_app_context()
  File "/Users/user/venv/lib/python3.7/site-packages/briefcase/commands/new.py", line 320, in build_app_context
    class_name = self.make_class_name(formal_name)
  File "/Users/user/venv/lib/python3.7/site-packages/briefcase/commands/new.py", line 84, in make_class_name
    if class_name[0].isdigit():
IndexError: string index out of range
`

**Expected behavior**
Ideally, this should return a concise and well structured error message.

**Environment:**
 - Operating System: MacOS

I would be happy to work on this myself. There is some overlap with #566

**Comment by freakboy3742** [comment]
Doing some housekeeping, this is a duplicate of #612. Although this is the earlier report, the description on #612 is more complete.
