### ISSUE TITLE
Packages not getting installed into virtual environment.

### ISSUE THREAD

**Issue by zhenry9** [beeware/briefcase#582]
**Describe the bug**
I'm trying to package an existing project with briefcase. I've created a virtual environment and listed my dependencies. When building or updating dependencies, everything appears to be downloaded and installed correctly. However when running the app I get a "module not found error". Running `pip freeze` confirms that the packages are not actually installed in the environment.

```
(.briefcase_env) PS C:\Users\Z\VSCode Projects\dweet2ser\dweet2ser> briefcase update -d

[dweet2ser] Updating dependencies...
Collecting colorama<1,>=0.4.4
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting Flask<2,>=1.1.2
  Using cached Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Flask-SocketIO<6,>=5.0.1
  Using cached Flask_SocketIO-5.0.1-py2.py3-none-any.whl (16 kB)
Collecting pyserial<4,>=3.5
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting requests<3,>=2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting termcolor<2,>=1.1.0
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting itsdangerous>=0.24
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting Werkzeug>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting click>=5.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting python-socketio>=5.0.2
  Using cached python_socketio-5.1.0-py2.py3-none-any.whl (53 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-win_amd64.whl (16 kB)
Collecting python-engineio>=4
  Using cached python_engineio-4.0.1-py2.py3-none-any.whl (50 kB)
Collecting bidict>=0.21.0
Installing collected packages: MarkupSafe, Werkzeug, python-engineio, Jinja2, itsdangerous, click, bidict, urllib3, python-socketio, idna, Flask, 
chardet, certifi, termcolor, requests, pyserial, Flask-SocketIO, colorama
Successfully installed Flask-1.1.2 Flask-SocketIO-5.0.1 Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 bidict-0.21.2 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 colorama-0.4.4 idna-2.10 itsdangerous-1.1.0 pyserial-3.5 python-engineio-4.0.1 python-socketio-5.1.0 requests-2.25.1 termcolor-1.1.0 urllib3-1.26.4

[dweet2ser] Updating application code...
Installing dweet2ser...

[dweet2ser] Application updated.
(.briefcase_env) PS C:\Users\Z\VSCode Projects\dweet2ser\dweet2ser> pip freeze
arrow==1.0.3
binaryornot==0.4.4
briefcase==0.3.5
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
cookiecutter==1.7.2
gitdb==4.0.5
GitPython==3.1.14
idna==2.10
Jinja2==2.11.3
MarkupSafe==1.1.1
poyo==0.5.0
python-dateutil==2.8.1
python-slugify==4.0.1
requests==2.25.1
six==1.15.0
smmap==3.0.5
text-unidecode==1.3
toml==0.10.2
urllib3==1.26.4
(.briefcase_env) PS C:\Users\Z\VSCode Projects\dweet2ser\dweet2ser> briefcase dev

[dweet2ser] Starting in dev mode...
Traceback (most recent call last):
  File "C:\Users\Z\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Z\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Z\VSCode Projects\dweet2ser\dweet2ser\dweet2ser\__main__.py", line 6, in <module>
    from . import local_device, remote_device, utils, webapp
  File "C:\Users\Z\VSCode Projects\dweet2ser\dweet2ser\dweet2ser\local_device.py", line 4, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

Unable to start application 'dweet2ser'
```

**To Reproduce**
Requires section:
```
requires = [
    "colorama>=0.4.4, <1",
    "Flask>=1.1.2, <2",
    "Flask-SocketIO>=5.0.1, <6",
    "pyserial>=3.5, <4",
    "requests>=2.25.1, <3",
    "termcolor>=1.1.0, <2"
]
```
1. Run `briefcase build`
2. Run `briefcase run` or `briefcase dev`
3. Verify with `pip freeze`

**Expected behavior**
The listed dependencies are installed into the virtual environment.

**Environment:**
 - Operating System:  Windows 10
 - Python version: 3.8

Maybe I'm missing something obvious. Appreciate the help!

**Comment by freakboy3742** [comment]
Thanks for the report - that's definitely odd; whatever is going on, it's not an obvious "oh, you forgot to do X" problem.

My suspicion is that this is something to do with *which* Python environment is running Briefcase. This is a problem on any OS, but Windows is particularly susceptible because of the way paths are resolved (see [this blog post](https://snarky.ca/why-you-should-use-python-m-pip/) for details). For example, Briefcase is clearly installing `colorama`; but colorama doesn't appear in your `pip freeze` list. This means there's (at least) 2 Python installs fighting for control.

It also looks like you're using Powershell - I don't have much experience with Powershell, so I don't know if that could be part of the complication here.

As a first thing to try: A lot of Python environment problems are resolved by using the `py` launcher. When you created the virtual environment, did you use `py -m venv <my env name>`, or did you run `python -m venv <my env name>`? If you did the latter - recreating your virtualenv using `py -m venv ...` may address the problem.

The next thing to try will be to run Briefcase itself using `py`; `py -m briefcase <other commands>`. 

If neither of those two things work... well... I'll need to do some more digging, I guess :-)

**Comment by sarthaksharma058439** [comment]
Hey ! I found very informative Beeware tutorial Series on youtube , you can check this channel @programmingfever , this channel posted beeware tutorial for beginners with mini projects, you can check this channel for your installed error for virtual environment.

**Comment by freakboy3742** [comment]
Closing due to lack of activity. This is almost certainly a case of having multiple Python installs, and pip not targeting the right environment.
