### ISSUE TITLE
briefcase run android failed

### ISSUE THREAD

**Issue by showkeyjar** [beeware/briefcase#590]
**Describe the bug**
when I use `briefcase run android`, it first download android emulator, but when I wait for few miniutes, it failed.
and give me a error:

`Creating Android emulator beePhone...

Obtaining device skin...
Traceback (most recent call last):
  File "D:\soft\anaconda3\envs\beauty\Scripts\briefcase-script.py", line 33, in <module>
    sys.exit(load_entry_point('briefcase==0.3.5', 'console_scripts', 'briefcase')())
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\briefcase-0.3.5-py3.8.egg\briefcase\__main__.py", line 11, in main
    command(**options)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\briefcase-0.3.5-py3.8.egg\briefcase\commands\run.py", line 77, in __call__
    state = self.run_app(app, **full_options(state, options))
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\briefcase-0.3.5-py3.8.egg\briefcase\platforms\android\gradle.py", line 161, in run_app      
    avd = self.android_sdk.create_emulator()
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\briefcase-0.3.5-py3.8.egg\briefcase\integrations\android_sdk.py", line 642, in create_emulator
    skin_tgz_path = self.command.download_url(
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\briefcase-0.3.5-py3.8.egg\briefcase\commands\base.py", line 484, in download_url
    response = self.requests.get(url, stream=True)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\requests-2.25.1-py3.8.egg\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\requests-2.25.1-py3.8.egg\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\requests-2.25.1-py3.8.egg\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\requests-2.25.1-py3.8.egg\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\requests-2.25.1-py3.8.egg\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\soft\anaconda3\envs\beauty\lib\site-packages\urllib3-1.26.4-py3.8.egg\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\soft\anaconda3\envs\beauty\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\soft\anaconda3\envs\beauty\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname`

**To Reproduce**
1. run 'briefcase run android'
2. when it download emulator make some network error
3. choose the emulator number that briefcase created

`In future, you can specify this device by running:

    briefcase run android -d @beePhone

Starting emulator beePhone...

Waiting for emulator to start.....
Android emulator was unable to start!

Try starting the emulator manually by running:

    C:\Users\56884\.briefcase\tools\android_sdk\emulator\emulator.exe @beePhone -dns-server 8.8.8.8

Resolve any problems you discover, then try running your app again. You may
find this page helpful in diagnosing emulator problems.

    https://developer.android.com/studio/run/emulator-acceleration#accel-vm`

**Expected behavior**
could briefcase check if the download is completed? 
If not, how can I remove the error emulator and restart or continue download?

**Environment:**
 - Operating System: windows 10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.5
   - Toga: 0.3.0.dev27

**Comment by showkeyjar** [comment]
it sames that nobody interesting this bug?

**Comment by freakboy3742** [comment]
@showkeyjar It's not that nobody is interested in the bug; it's that we have limited resources.

Is there a way to remove the old emulator? Sure - briefcase is a fairly thin wrapper around the default Android tools, so you can use those to manage your emulator images. 

Alternatively, you could create a new emulator; this would leave the original "broken" emulator on your machine, but that won't break anything.

Interestingly, I think you'll find that the problem *isnt'* the emulator itself - it's the emulator skin. You may find the emulator actually continues to work, even though the skin files are incomplete. Your report doesn't describe whether you've tried this, though.

Could Briefcase improve its error handling of this edge case? Certainly. We're open to any patch that improves the developer experience.

**Comment by showkeyjar** [comment]
@freakboy3742 thank you for your answer, I'll have a try.

**Comment by freakboy3742** [comment]
@showkeyjar Did you have any success when you retried this?

**Comment by dodiko1d** [comment]
> @freakboy3742 thank you for your answer, I'll have a try.

Delete .briefcase from user folder.

**Comment by freakboy3742** [comment]
Closing due to lack of response from the original reporter.
