### ISSUE TITLE
Cannot find dependency in the Python 3 standard library (wsgiref)

### ISSUE THREAD

**Issue by lukasvasadi** [beeware/briefcase#600]
My application uses the [gcsfs](https://pypi.org/project/gcsfs/) package for accessing Google Cloud Storage. This package in turn has dependency [google-auth-oauthlib](https://pypi.org/project/google-auth-oauthlib/), relies on a module called [wsgiref](https://pypi.org/project/wsgiref/). Previously, `wsgiref` had to be installed manually for Python 2—however, it is now available in the Python 3 standard library. The application runs as expected in developer mode (`briefcase dev`), but returns a ModuleNotFoundError in the crash report when run as a packaged app (`briefcase run`):

```
Traceback (most recent call last):
  File "ZarrViewer.app/Contents/Resources/app/zarrviewer/__main__.py", line 1, in <module>
    from zarrviewer.app import main
  File "ZarrViewer.app/Contents/Resources/app/zarrviewer/app.py", line 6, in <module>
    from zarrviewer.controller import Controller
  File "ZarrViewer.app/Contents/Resources/app/zarrviewer/controller.py", line 8, in <module>
    from zarrviewer.model import Plates_model, Wells_model, Well_model
  File "ZarrViewer.app/Contents/Resources/app/zarrviewer/model.py", line 11, in <module>
    from zarrviewer.workers import Retrieve_zarrs_worker
  File "ZarrViewer.app/Contents/Resources/app/zarrviewer/workers.py", line 4, in <module>
    import gcsfs
  File "ZarrViewer.app/Contents/Resources/app_packages/gcsfs/__init__.py", line 5, in <module>
    from .core import GCSFileSystem
  File "ZarrViewer.app/Contents/Resources/app_packages/gcsfs/core.py", line 22, in <module>
    from .credentials import GoogleCredentials
  File "ZarrViewer.app/Contents/Resources/app_packages/gcsfs/credentials.py", line 8, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "ZarrViewer.app/Contents/Resources/app_packages/google_auth_oauthlib/__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "ZarrViewer.app/Contents/Resources/app_packages/google_auth_oauthlib/interactive.py", line 24, in <module>
    import google_auth_oauthlib.flow
  File "ZarrViewer.app/Contents/Resources/app_packages/google_auth_oauthlib/flow.py", line 65, in <module>
    import wsgiref.simple_server
ModuleNotFoundError: No module named 'wsgiref'
```

**To Reproduce**
This error can be reproduced simply by packaging any application that imports `gcsfs`. I recommend creating the helloworld app from the beginner tutorial and adding `import gcsfs` in `app.py`. The script should execute normally in developer mode, but produce the same traceback when running the packaged version.

**Environment:**
 - Operating System: macOS Catalina Version 10.15.7
 - Python version: 3.7.8 or 3.9.4 (both tested)
 - Software versions:
   - briefcase==0.3.5
   - toga-cocoa==0.3.0.dev20
    - gcsfs==2021.7.0
    - decorator==4.3

**Comment by freakboy3742** [comment]
Thanks for the report! Strictly, this isn't a bug - it's "working as expected", as [`wsgiref` is explicitly excluded from the support package on macOS and iOS](https://github.com/beeware/Python-Apple-support/blob/dev/patch/Python/release.common.exclude#L22). 

That said - if packages like `gcsfs` are using `wsgiref` because it contains useful WSGI/HTTP utility methods, then we may need to reconsider the inclusion of `wsgiref` in the support package. It's only 68k of code, and it's pure Python, so it's probably worth it.

I'll also move this ticket to the Python-Apple-support repo, since that's where the underlying problem lies.
