### ISSUE TITLE
Android emulator not supported on M1 hardware

### ISSUE THREAD

**Issue by GitHubofkangk** [beeware/briefcase#616]
**Describe the bug**

Attempting to run the android emulator on Mac M1 hardware fails with the error

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/likang/.briefcase/tools/android_sdk/emulator/emulator'.
```

**To Reproduce**
```bash
(venv) ➜  BeeWare cd beeware-tutorial 
(venv) ➜  beeware-tutorial cd heloworld       
(venv) ➜  heloworld briefcase dev        # run in development

[heloworld] Starting in dev mode...
Hello 
(venv) ➜  heloworld briefcase build android      # build android
[heloworld] Building Android APK...
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :app:externalNativeBuildDebug
Build native-lib_armeabi-v7a
Build native-lib_arm64-v8a
Build native-lib_x86
Build native-lib_x86_64

BUILD SUCCESSFUL in 17s
31 actionable tasks: 2 executed, 29 up-to-date

[heloworld] Built android/gradle/Hello World/app/build/outputs/apk/debug/app-debug.apk
(venv) ➜  heloworld briefcase run android          # run android
Traceback (most recent call last):
  File "/Users/likang/PycharmProjects/BeeWare/venv/bin/briefcase", line 8, in <module>
    sys.exit(main())
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/__main__.py", line 11, in main
    command(**options)
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/commands/run.py", line 77, in __call__
    state = self.run_app(app, **full_options(state, options))
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/platforms/android/gradle.py", line 151, in run_app
    device, name, avd = self.android_sdk.select_target_device(
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/integrations/android_sdk.py", line 449, in select_target_device
    for avd in self.emulators():
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/integrations/android_sdk.py", line 331, in emulators
    output = self.command.subprocess.check_output(
  File "/Users/likang/PycharmProjects/BeeWare/venv/lib/python3.9/site-packages/briefcase/integrations/subprocess.py", line 85, in check_output
    return self._subprocess.check_output(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/likang/.briefcase/tools/android_sdk/emulator/emulator'
```
**Expected behavior**
run in android emulator

**Environment:**
 - Operating System: macOS Big Sur apple m1
 - Python version:3.9
 - Software versions:
   - Briefcase:0.3.5
   - Toga:
   - ...

**Comment by freakboy3742** [comment]
Android has only recently added support for running the Android emulator on M1 Mac hardware; Briefcase has not yet been updated to provide this support. I suspect this *should* be a matter of [updating the SDK Manager components](https://github.com/beeware/briefcase/blob/master/src/briefcase/integrations/android_sdk.py#L310) to reflect the M1 hardware target instead of x86.

**Comment by zili55** [comment]
@freakboy3742 Hi, I would like to start work on this issue, it is possible to test somehow without M1 hardware?

**Comment by freakboy3742** [comment]
@zili Unfortunately not - pretty much by definition, the M1 emulator will only run on M1 hardware.

**Comment by zili55** [comment]
ok then someone with M1 hardware can take this issue
