### ISSUE TITLE
Downloading windows template returns `Remote named 'origin' didn't exist`

### ISSUE THREAD

**Issue by HeavyWolfPL** [beeware/briefcase#663]
**Describe the bug**
While following the tutorial I've encountered no issues on my PC (where the only software difference is Win 10 Home), but downloading the Windows app template on my laptop seems to throw `ValueError: Remote named 'origin' didn't exist`. 

This does not happen with other platforms' templates, only Windows.

**Steps I've taken**
- Reinstalled Python (removed lib folder) and Git
- Copied all project files (with template) from my PC to Laptop
- Copied Python packages from PC to Laptop
- Tried on a fresh virtual machine (with the same software versions) and it works there too

**To Reproduce**
1. Follow the tutorial till `briefcase create`
2. Run the mentioned command
3. Error happens

**Expected behavior**
Template should be downloaded, and the program would proceed to the next step.

**Error snippet**
```
(beeware-venv) C:\Programowanie\Projekty\Python\BeeWare\xd>briefcase create

[xd] Generating application template...
Using app template: https://github.com/beeware/briefcase-windows-msi-template.git, branch 3.8
Traceback (most recent call last):
  File "C:\Users\Wafel\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Wafel\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Programowanie\Projekty\Python\BeeWare\beeware-venv\Scripts\briefcase.exe\__main__.py", line 7, in <module>
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\briefcase\__main__.py", line 11, in main
    command(**options)
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\briefcase\commands\create.py", line 695, in __call__
    state = self.create_app(app, **full_options(state, options))
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\briefcase\commands\create.py", line 646, in create_app
    self.generate_app_template(app=app)
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\briefcase\commands\create.py", line 270, in generate_app_template
    cached_template = self.update_cookiecutter_cache(
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\briefcase\commands\base.py", line 557, in update_cookiecutter_cache
    remote = repo.remote(name='origin')
  File "c:\programowanie\projekty\python\beeware\beeware-venv\lib\site-packages\git\repo\base.py", line 358, in remote
    raise ValueError("Remote named '%s' didn't exist" % name)
ValueError: Remote named 'origin' didn't exist
```

**Environment:**
 - Operating System: Win 10 Pro
 - Python version: 3.8.10
 - Software versions:
   - Briefcase: 0.3.5
   - GitPython: 3.1.26
   - Git: 2.35.1.2

**Comment by freakboy3742** [comment]
This has all the signs of a corrupted Cookiecutter repository - I can't think of any set of circumstances that would lead to "origin does not exist" on a git repository that doesn't involve something breaking on an earlier clone.

If you delete the `.cookiecutters/briefcase-windows-msi-template` directory (contained in your user home directory) and re-run, does the error persist?
