### ISSUE TITLE
Daemon error response when executing 'briefcase build'

### ISSUE THREAD

**Issue by csy1127690357** [beeware/briefcase#715]
**Describe the bug**
A docker daemon error occurs when executing `briefcase build`, as follows
```
briefcase build             

[helloworld] Building AppImage...

[helloworld] Entering Docker context...
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/home/brutus/.briefcase/tools/linuxdeploy-x86_64.AppImage": permission denied: unknown.
ERRO[0000] error waiting for container: context canceled 

Error while building app helloworld.
```

**To Reproduce**
1.When executing `briefcase create` according to the learning tutorial, the following error occurs
```
*************************************************************************
** WARNING: Unable to determine the version of Docker                  **
*************************************************************************

    Briefcase will proceed, assuming everything is OK. If you
    experience problems, this is almost certainly the cause of those
    problems.

    Please report this as a bug at:

      https://github.com/beeware/briefcase/issues/new

    In your report, please including the output from running:

      docker --version

    from the command prompt.

*************************************************************************
```
But in the end it can still be created successfully
`[helloworld] Created linux/appimage/Hello World`

2.Then execute `briefcase build` to get the above error.

**Environment:**
 - Operating System:`Linux kali 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux`
 - Python version:`Python 3.9.12`
 - Software versions:
   - Briefcase:0.3.6

**Additional context**
```
docker ps -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED             STATUS                     PORTS     NAMES
a7afb06458f3   briefcase/com.example.helloworld:py3.9   "/home/brutus/.brief…"   13 seconds ago      Created                              dazzling_almeida
d6a14976aa78   briefcase/com.example.helloworld:py3.9   "/home/brutus/.brief…"   About an hour ago   Created                              elated_herschel
e9da976c04df   briefcase/com.example.helloworld:py3.9   "python3.9 -m pip in…"   2 hours ago         Exited (0) 2 hours ago               quizzical_saha
6e954005b87c   5c615b6de854                             "/bin/sh -c 'apt-get…"   2 hours ago         Exited (100) 2 hours ago             nice_williams
ce785f2af939   5c615b6de854                             "/bin/sh -c 'apt-get…"   3 hours ago         Exited (100) 2 hours ago             inspiring_curran


```

**Comment by freakboy3742** [comment]
You've included a copy of a warning message, but you haven't provided the one piece of information that the warning message asked for - the output of `docker -version`. 

The "permission denied" error is one that I haven't seen before, but I suspect it will be related to the user that is running docker, and the permissions

* Are you running docker as sudo?
* Does the `~/.briefcase/tools` folder exist?
* Does `~/.briefcase/tools/linuxdeploy-x86_64.AppImage` exist, and does it have read and execute permission for the user that is running docker?

**Comment by csy1127690357** [comment]
docker version:`Docker version 20.10.14+dfsg1, build a224086`

is running with sudo privileges.

The folder and file `~/.briefcase/tools/linuxdeploy-x86_64.AppImage` exist. After granting the 755 permission, no further error is reported, but a new problem has occurred, as follows
```
briefcase build

[helloworld] Building AppImage...

[helloworld] Entering Docker context...
exec /home/brutus/.briefcase/tools/linuxdeploy-x86_64.AppImage: exec format error

Error while building app helloworld.
```

**Comment by freakboy3742** [comment]
Thanks for the docker version detail. I'll need to look into why this is causing a problem with the Docker version check.

Regarding sudo: I should have been more clear. I know that there are some sudo group changes needed to get Docker working at all; what I meant to ask was whether you are using `sudo briefcase run` or doing anything else that might cause your briefcase invocation to be running as root. This is a very common cause of problems, and when those problems occur, it usually manifests as a permissions issue.

Lastly - if you're getting exec format errors, and/or the executable permission wasn't set, it suggests that the download was corrupted. If this happened, it should have been reported during the initial build, but it may not have been obvious that it was a problem. Try manually deleting the linuxdeploy AppImage from the ~/.briefcase/tools folder and retrying the build - that should re-download the binary (and hopefully, this time it won't be corrupted). If it doesn't work, delete the file again, then send the full log of the output of running `briefcase build`,

**Comment by csy1127690357** [comment]
Thank you very much, the problem has been resolved, it is indeed because LinuxDeploy Appimage file is damaged, delete it and re-download,the problem solved.

**Comment by freakboy3742** [comment]
Awesome - thanks for letting us know. I'll close the ticket on that basis.

Following up one loose thread: The docker version string you've produced shouldn't pose a problem as far as I can see. Can you provide the full output of `docker --version` (including any content before or after the `Docker version...` line? The only way I can see the check failing is if there was something else being output to stdout as part of calling that command.

**Comment by csy1127690357** [comment]
```
docker version
Client:
 Version:           20.10.14+dfsg1
 API version:       1.41
 Go version:        go1.18
 Git commit:        a224086
 Built:             Wed Mar 30 16:07:00 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18
  Git commit:       87a90dc
  Built:            Wed Mar 30 16:07:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.2~ds1
  GitCommit:        1.6.2~ds1-1
 runc:
  Version:          1.1.1+ds1
  GitCommit:        1.1.1+ds1-1
 docker-init:
  Version:          0.19.0
  GitCommit:        

```

**Comment by freakboy3742** [comment]
Sorry - `docker --version`, not `docker version`.

**Comment by csy1127690357** [comment]
Is it this one？
```
┌──(root💀kali)-[~/Desktop]
└─# docker --version
Docker version 20.10.14+dfsg1, build a224086
```

**Comment by freakboy3742** [comment]
That's what I was looking for... but as far as I can make out, that should be identifying the version correctly. When you run Briefcase, are you still seeing the warning about not being able to identify the Docker version?

**Comment by csy1127690357** [comment]
It won't appear now, and it should also be caused by the previous file corruption.
Also, there is currently a new problem in `briefcase run`

```
[helloworld] Starting app...


** (process:5364): WARNING **: 14:24:42.207: Failed to load shared library 'libpango-1.0.so.0' referenced by the typelib: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2
Traceback (most recent call last):
  File "/tmp/.mount_Hello_RNLRuX/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_Hello_RNLRuX/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_Hello_RNLRuX/usr/app/helloworld/__main__.py", line 4, in <module>
    main().main_loop()
  File "/tmp/.mount_Hello_RNLRuX/usr/app/helloworld/app.py", line 42, in main
    return HelloWorld()
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga/app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga/platform.py", line 41, in get_platform_factory
    from toga_gtk import factory
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga_gtk/factory.py", line 1, in <module>
    from .app import App, DocumentApp, MainWindow
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga_gtk/app.py", line 13, in <module>
    from .keys import gtk_accel
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga_gtk/keys.py", line 3, in <module>
    from .libs import Gdk
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga_gtk/libs/__init__.py", line 1, in <module>
    from .gtk import *  # noqa: F401, F403
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/toga_gtk/libs/gtk.py", line 5, in <module>
    from gi.repository import Gtk, Gdk, GdkPixbuf, Gio, GLib, GObject  # noqa: F401, E402
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Hello_RNLRuX/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/importer.py", line 149, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/tmp/.mount_Hello_RNLRuX/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/importer.py", line 150, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/tmp/.mount_Hello_RNLRuX/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/tmp/.mount_Hello_RNLRuX/usr/app_packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

Unable to start app helloworld.
```
It's about missing dependencies at runtime, I noticed that you've created a new consolidation ticket to address this issue, looking forward to getting it resolved soon.
