### ISSUE TITLE
Hello World fails at “xcrun: error: unable to find utility "xcodebuild"”

### ISSUE THREAD

**Issue by benf-wspdigital** [beeware/briefcase#72]
Following the [Briefcase tutorial 0 for iOS](https://briefcase.readthedocs.io/en/latest/tutorials/tutorial-0.html#ios), I get a failure when attempting to “put it in a briefcase”.

```
$ python3 -m setup ios -s
running ios

[…]
Installation complete.
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/benfinney/Projects/python/Briefcase/tutorial/helloworld/setup.py", line 79, in <module>
    'toga-django',
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/benfinney/.virtualenvs/briefcase-tutorial/lib/python3.5/site-packages/briefcase/app.py", line 345, in run
    self.build_app()
  File "/Users/benfinney/.virtualenvs/briefcase-tutorial/lib/python3.5/site-packages/briefcase/ios.py", line 139, in build_app
    if not self.has_required_xcode_version():
  File "/Users/benfinney/.virtualenvs/briefcase-tutorial/lib/python3.5/site-packages/briefcase/ios.py", line 130, in has_required_xcode_version
    for v in output.split('\n')[0].split(' ')[1].split('.')[:2]
IndexError: list index out of range

$ xcrun --version
xcrun version 32.

$ xcrun --show-sdk-path

```

The tutorial doesn't give any indication that I need to so anything special to get Xcode commands working; it goes straight from writing my Python code, to running the above Distutils command.

**Comment by freakboy3742** [comment]
Do you have the Xcode command line tools installed? It's an extension package that isn't part of the base Xcode install. It's an oversight that we don't mention that that package is required. We might even be able to automate the processs of *getting* it installed by requesting the feature from Xcode itself - I know other tools do this.

**Comment by freakboy3742** [comment]
The 0.3 development branch adds checks to see if `xcodebuild` is installed before attempting to invoke it; this error should no longer occur.
