### ISSUE TITLE
"briefcase run" fails: RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'

### ISSUE THREAD

**Issue by Jason-XII** [beeware/briefcase#748]
**Describe the bug**
I'm using briefcase's example code. When I try "briefcase run", it says "unable to start app hello world".

**Error Message**
```
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app\helloworld\__main__.py", line 4, in <module>
    main().main_loop()
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app\helloworld\app.py", line 27, in main
    return HelloWorld()
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga\app.py", line 272, in __init__
    self.factory = get_platform_factory(factory)
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga\platform.py", line 53, in get_platform_factory
    from toga_winforms import factory
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\factory.py", line 1, in <module>
    from .app import App, MainWindow
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\app.py", line 8, in <module>
    from .keys import toga_to_winforms_key
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\keys.py", line 6, in <module>
    from .libs import WinForms
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\libs\__init__.py", line 1, in <module>
    from .fonts import (  # noqa: F401
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\libs\fonts.py", line 13, in <module>
    from .winforms import (
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\toga_winforms\libs\winforms.py", line 3, in <module>
    import clr
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\clr.py", line 6, in <module>
    load()
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "E:\OneDrive\编程\helloworld\windows\msi\Hello World\src\\app_packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

I executed:
```
briefcase new
briefcase create
briefcase build
briefcase run
```

**Comment by Jason-XII** [comment]
However, it turns out that packaging and installing as an executable was fine.

**Comment by freakboy3742** [comment]
Thanks for the report.

When you created the bug report, there was a template that we need you to follow. The details that are requested are *vital* for us to determine what has gone on.

Are you able to provide version numbers for:
* Windows
* Python
* briefcase
* toga
 
The discussion where you also posted this stack trace [included a specific request for debugging information](https://github.com/beeware/briefcase/discussions/729#discussioncomment-2697157); if you're able to provide that as well, it would be very helpful.

**Comment by freakboy3742** [comment]
Closing due to lack of response.
