### ISSUE TITLE
module 'toga_android.factory' has no attribute 'OptionContainer'

### ISSUE THREAD

**Issue by IssacCzy** [beeware/briefcase#847]
## Describe the bug
use toga.OptionContainer() in my beeware demo project
```
def startup(self):
        self.main_window = toga.MainWindow(self.name)

        container = toga.OptionContainer()

        c_4_tab1 = toga.Label(text='content 4 tab1')
        c_4_tab2 = toga.Label(text='content 4 tab2')

        container.add('tab1', c_4_tab1)
        container.add('tab2', c_4_tab2)

        self.main_window.content = container
        self.main_window.show()
```

## To Reproduce
* 1. Open Anaconda Prompt
* 2. Activate env：beewareGUI
* 3. briefcase create android
* 4. briefcase build android -u
* 5. briefcase run android -u
* 6. Select device

## Expected behavior
A app with  toga.OptionContainer() page will be open
**but**
Wait a moment：Page rendering is in pseudo dead state
check Anaconda Prompt console log:
```
08-25 01:51:28.233  3008  3008 I Python  : Python app launched & stored in Android Activity class
08-25 01:51:28.246  3008  3008 E Python  : Application quit abnormally!
08-25 01:51:28.246  3008  3008 E Python  : Traceback (most recent call last):
08-25 01:51:28.246  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/stdlib/lib/python3.7/runpy.py", line 193, in
_run_module_as_main
08-25 01:51:28.246  3008  3008 E Python  :     "__main__", mod_spec)
08-25 01:51:28.246  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/stdlib/lib/python3.7/runpy.py", line 85, in _run_code
08-25 01:51:28.247  3008  3008 E Python  :     exec(code, run_globals)
08-25 01:51:28.247  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app/beeware/__main__.py", line 4, in <module>
08-25 01:51:28.247  3008  3008 E Python  :     main().main_loop()
08-25 01:51:28.247  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app_packages/toga/app.py", line 517, in main_loop
08-25 01:51:28.247  3008  3008 E Python  :     self._impl.main_loop()
08-25 01:51:28.248  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app_packages/toga_android/app.py", line 187, in
main_loop
08-25 01:51:28.248  3008  3008 E Python  :     self.create()
08-25 01:51:28.248  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app_packages/toga_android/app.py", line 176, in
create
08-25 01:51:28.248  3008  3008 E Python  :     self.interface.startup()
08-25 01:51:28.248  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app/beeware/app.py", line 14, in startup
08-25 01:51:28.248  3008  3008 E Python  :     container = toga.OptionContainer()
08-25 01:51:28.249  3008  3008 E Python  :   File "/data/user/0/com.example.beeware/files/python/user_code/app_packages/toga/widgets/optioncontainer.py",
line 151, in __init__
08-25 01:51:28.249  3008  3008 E Python  :     self._impl = self.factory.OptionContainer(interface=self)
08-25 01:51:28.249  3008  3008 E Python  : AttributeError: module 'toga_android.factory' has no attribute 'OptionContainer'
08-25 01:51:28.249  3008  3008 D MainActivity: Python.run() end
08-25 01:51:28.249  3008  3008 D MainActivity: startPython() end
08-25 01:51:28.249  3008  3008 D MainActivity: user code onCreate() start
08-25 01:51:28.250  3008  3008 D Python  : Native invocation 139119772933648 :: onCreate
08-25 01:51:28.250  3008  3008 I Python  : Toga app: onCreate
```
## key point
```
AttributeError: module 'toga_android.factory' has no attribute 'OptionContainer'
```

> when i take out the widget OptionContainer，The world is beautiful again
> I have conducted the same test in three different projects, all of which have this problem

**Environment:**
 - Operating System: Windows10 - Windows Feature Experience Pack 120.2212.4180.0
 - Python version:  3.7.0
 - Software versions: 
   - Briefcase: 0.3.8
   - beeware: 0.3.0
   - Toga: 0.3.0.dev36

**Comment by freakboy3742** [comment]
The Android backend doesn't have an OptionContainer widget yet.

**Comment by IssacCzy** [comment]
@freakboy3742 
3 thanks 4 your answer
And can you give me a widget list which supported by android ? It can save me a lot of testing work，3QU very much!

**Comment by freakboy3742** [comment]
There's a support table in the docs: https://toga.readthedocs.io/en/latest/reference/widgets_by_platform.html

**Comment by IssacCzy** [comment]
3QU!
