### ISSUE TITLE
Windows Toga Apps Throw `AttributeError` After `clr_loader` `v0.2.3` Release

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#861]
**Describe the bug**
The error below is logged when running `briefcase dev` or `briefcase run` for Windows Toga Apps since the release of `clr_loader==0.2.3`.

Error: `AttributeError: module 'clr_loader' has no attribute 'wrappers'`

<details>
<summary>Full Error Log</summary>

```
❯ briefcase new --no-input; cd helloworld; briefcase dev

Generating a new application 'Hello World'
Using existing template (sha c235ca02a66b8a27ed5641f08801c9ecf293a66e, updated Thu Aug  4 07:36:42 2022)

Application 'Hello World' has been generated. To run your application, type:

    cd helloworld
    briefcase dev

[helloworld] Installing dependencies...
Collecting toga-winforms>=0.3.0.dev34
  Using cached toga_winforms-0.3.0.dev36-py3-none-any.whl (327 kB)
Collecting toga-core==0.3.0.dev36
  Using cached toga_core-0.3.0.dev36-py3-none-any.whl (493 kB)
Collecting pythonnet>=3.0.0a1
  Using cached pythonnet-3.0.0rc4-py3-none-any.whl (250 kB)
Collecting travertino>=0.1.3
  Using cached travertino-0.1.3-py3-none-any.whl (15 kB)
Collecting clr-loader>=0.1.7
  Using cached clr_loader-0.2.3-py3-none-any.whl (50 kB)
Collecting cffi>=1.13
  Using cached cffi-1.15.1-cp310-cp310-win_amd64.whl (179 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: travertino, pycparser, toga-core, cffi, clr-loader, pythonnet, toga-winforms
Successfully installed cffi-1.15.1 clr-loader-0.2.3 pycparser-2.21 pythonnet-3.0.0rc4 toga-core-0.3.0.dev36 toga-winforms-0.3.0.dev36 travertino-0.1.3
Installing dev dependencies... done

[helloworld] Starting in dev mode...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Russell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\Russell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Russell\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Russell\tmp\beeware\helloworld\src\helloworld\__main__.py", line 4, in <module>
    main().main_loop()
  File "C:\Users\Russell\tmp\beeware\helloworld\src\helloworld\app.py", line 27, in main
    return HelloWorld()
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga\app.py", line 278, in __init__
    self.factory = get_platform_factory(factory)
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga\platform.py", line 53, in get_platform_factory
    from toga_winforms import factory
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\factory.py", line 1, in <module>
    from .app import App, MainWindow
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\app.py", line 7, in <module>
    from .keys import toga_to_winforms_key
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\keys.py", line 6, in <module>
    from .libs import WinForms
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\libs\__init__.py", line 1, in <module>
    from .fonts import (  # noqa: F401
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\libs\fonts.py", line 13, in <module>
    from .winforms import (
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\toga_winforms\libs\winforms.py", line 3, in <module>
    import clr
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\clr.py", line 5, in <module>
    from pythonnet import load
  File "C:\Users\Russell\github\beeware\briefcase\venv-3.10-beeware-briefcase\lib\site-packages\pythonnet\__init__.py", line 9, in <module>
    _LOADER_ASSEMBLY: Optional[clr_loader.wrappers.Assembly] = None
AttributeError: module 'clr_loader' has no attribute 'wrappers'

Unable to start application 'helloworld'
```

</details>

**To Reproduce**
`briefcase new --no-input; cd helloworld; briefcase dev`

**Expected behavior**
App should not crash.

This will/should automatically resolve itself when `Pythonnet` cuts their next 3.0.x [release](https://github.com/pythonnet/pythonnet/releases).

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.10
 - Software versions:
   - Briefcase: 6acfdd86a169d0964978ea2aa01dc70aabce864f
   - Toga: `toga-winforms v0.3.0.dev36`

<details>
<summary>All Installed Python Packages</summary>

```
Package            Version     Editable project location
------------------ ----------- -----------------------------------------
arrow              1.2.3
attrs              22.1.0
binaryornot        0.4.4
briefcase          0.3.9       C:\Users\Russell\github\beeware\briefcase
certifi            2022.9.14
cffi               1.15.1
cfgv               3.3.1
chardet            5.0.0
charset-normalizer 2.1.1
click              8.1.3
clr-loader         0.2.3
colorama           0.4.5
commonmark         0.9.1
cookiecutter       2.1.1
coverage           6.4.4
distlib            0.3.6
filelock           3.8.0
gitdb              4.0.9
GitPython          3.1.27
identify           2.5.5
idna               3.4
iniconfig          1.1.1
Jinja2             3.1.2
jinja2-time        0.2.0
MarkupSafe         2.1.1
nodeenv            1.7.0
packaging          21.3
pip                22.2.2
platformdirs       2.5.2
pluggy             1.0.0
pre-commit         2.20.0
psutil             5.9.2
py                 1.11.0
pycparser          2.21
Pygments           2.13.0
pyparsing          3.0.9
pytest             7.1.3
pytest-cov         3.0.0
pytest-tldr        0.2.4
python-dateutil    2.8.2
python-slugify     6.1.2
pythonnet          3.0.0rc4
PyYAML             6.0
requests           2.28.1
rich               12.5.1
setuptools         65.3.0
six                1.16.0
smmap              5.0.0
text-unidecode     1.3
toga-core          0.3.0.dev36
toga-winforms      0.3.0.dev36
toml               0.10.2
tomli              2.0.1
tomli_w            1.0.0
tox                3.26.0
travertino         0.1.3
urllib3            1.26.12
virtualenv         20.16.5
wheel              0.37.1
```

</details>

## Workaround
* Use the previous release of `clr_loader`:
  * Add `clr_loader==0.1.7` in the `tool.briefcase.app.<app_name>.windows` section in `pyproject.toml`
* Use the bleeding edge of `pythonnet`:
  * Add `git+https://github.com/pythonnet/pythonnet@release` in the `tool.briefcase.app.<app_name>.windows` section in `pyproject.toml`

**Comment by rmartin16** [comment]
`Pythonnet v3.0.0rc5` reeleased and contains support for `clr_loader v0.2.3`.
