### ISSUE TITLE
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by rmartin16** [beeware/briefcase#868]
**Describe the bug**
The `cgi` module is being deprecated in Python 3.13.

<details>
<summary>DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13</summary>

```
❯ pytest -Werror
==============================================================================
CRITICAL: 
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.11.0rc1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/user/github/rmartin16/briefcase/venv-3.11.0rc1-rmartin16-briefcase/lib/python3.11/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/user/github/rmartin16/briefcase/tests/commands/base/conftest.py", line 3, in <module>
    from briefcase.commands.base import BaseCommand
  File "/home/user/github/rmartin16/briefcase/src/briefcase/commands/__init__.py", line 1, in <module>
    from .build import BuildCommand  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/github/rmartin16/briefcase/src/briefcase/commands/build.py", line 5, in <module>
    from .base import BaseCommand, full_options
  File "/home/user/github/rmartin16/briefcase/src/briefcase/commands/base.py", line 28, in <module>
    from briefcase.integrations.base import ToolCache
  File "/home/user/github/rmartin16/briefcase/src/briefcase/integrations/__init__.py", line 1, in <module>
    from . import (
  File "/home/user/github/rmartin16/briefcase/src/briefcase/integrations/download.py", line 1, in <module>
    from cgi import parse_header
  File "/home/user/.pyenv/versions/3.11.0rc1/lib/python3.11/cgi.py", line 57, in <module>
    warnings._deprecated(__name__, remove=(3,13))
  File "/home/user/.pyenv/versions/3.11.0rc1/lib/python3.11/warnings.py", line 514, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

------------------------------------------------------------------------------
Ran 0 tests in 0.14s
```
</details>

**To Reproduce**
Run `pytest -Werror`

**Expected behavior**
Replace functionality provided by `cgi.parse_header()` in [`download.py`](https://github.com/beeware/briefcase/blob/main/src/briefcase/integrations/download.py#L59). The apparent [official recommendation](https://peps.python.org/pep-0594/#cgi)....which at least appears very interesting at face value...

**Comment by freakboy3742** [comment]
Whoever fixes this: #867 added (or will add, as soon as it is merged) a warning filter in the pytest configuration in `pyproject.toml` to silence this warning. That filter clause should be removed as part of any fix for this problem.
