### ISSUE TITLE
Windows: `briefcase dev` crashes on shutdown

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase#987]
I'm not sure when this started, but it's been affecting all my apps since at least a week ago. It only affects `briefcase dev` -- `briefcase run` works fine.

I followed the first page of the [BeeWare tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-1.html) in a fresh virtual env. When I ran `briefcase dev` for the first time, everything started up fine:
```
Successfully installed attrs-22.1.0 cffi-1.15.1 clr-loader-0.2.4 exceptiongroup-1.0.4 iniconfig-1.1.1 pluggy-1.0.0 pycparser-2.21 pytest-7.2.0 pythonnet-3.0.1 toga-core-0.3.0.dev39 toga-winforms-0.3.0.dev39 travertino-0.1.3
Installing dev requirements... done

[helloworld] Starting in dev mode...
===========================================================================
```
But when I closed the app window, I got this error:
```
Windows fatal exception: access violation

Current thread 0x00001c04 (most recent call first):
  File "C:\Users\smith\cygwin\.venv\bw-test\lib\site-packages\clr_loader\types.py", line 64 in __call__
  File "C:\Users\smith\cygwin\.venv\bw-test\lib\site-packages\pythonnet\__init__.py", line 157 in unload

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   at Python.Runtime.ManagedType.TryFreeGCHandle(BorrowedReference reflectedClrObject, BorrowedReference type)
   at Python.Runtime.Runtime.NullGCHandles(IEnumerable`1 objects)
   at Python.Runtime.Runtime.TryCollectingGarbage(Int32 runs, Boolean forceBreakLoops)
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.Loader.Shutdown(IntPtr data, Int32 size)

Problem running application 'helloworld'

Log saved to C:\Users\smith\cygwin\tmp\helloworld\logs\briefcase.2022_12_03-19_43_59.dev.log
```
[briefcase.2022_12_03-19_43_59.dev.log](https://github.com/beeware/briefcase/files/10147285/briefcase.2022_12_03-19_43_59.dev.log)
  
**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0c5372f20f4
   - Toga: 0.3.0.dev39

**Comment by rmartin16** [comment]
Potential root cause / workaround: https://github.com/pythonnet/pythonnet/issues/1977#issuecomment-1335132947
