### ISSUE TITLE
error Tutorial 1 

### ISSUE THREAD

**Issue by JSHZT** [beeware/briefcase#990]
Hello! I followed the tutorial 1 but got the following error,The following is the saved log, so what is the reason?

```
Date/Time:       2022-12-06 22:38:07 
Command line:    /home/jshzt/miniconda3/envs/sqlapk/bin/briefcase dev

OS Release:      Linux 5.15.0-56-generic
OS Version:      #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022
Architecture:    x86_64
Platform:        Linux-5.15.0-56-generic-x86_64-with-glibc2.17

Python exe:      /home/jshzt/miniconda3/envs/sqlapk/bin/python
Python version:  3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0]
Virtual env:     False
Conda env:       True

Briefcase:       0.3.11
Target platform: linux
Target format:   None

Environment Variables:
    CHROME_DESKTOP=code-url-handler.desktop
    COLORTERM=truecolor
    CONDA_DEFAULT_ENV=sqlapk
    CONDA_EXE=/home/jshzt/miniconda3/bin/conda
    CONDA_PREFIX=/home/jshzt/miniconda3/envs/sqlapk
    CONDA_PREFIX_1=/home/jshzt/miniconda3
    CONDA_PROMPT_MODIFIER=(sqlapk) 
    CONDA_PYTHON_EXE=/home/jshzt/miniconda3/bin/python
    CONDA_SHLVL=2
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    DESKTOP_SESSION=ubuntu
    DISPLAY=:0
    GDK_BACKEND=x11
    GDMSESSION=ubuntu
    GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/code.desktop
    GIO_LAUNCHED_DESKTOP_FILE_PID=37229
    GIT_ASKPASS=********************
    GJS_DEBUG_OUTPUT=stderr
    GJS_DEBUG_TOPICS=JS ERROR;JS LOG
    GNOME_DESKTOP_SESSION_ID=this-is-deprecated
    GNOME_SHELL_SESSION_MODE=ubuntu
    GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
    GTK_MODULES=gail:atk-bridge
    HOME=/home/jshzt
    IM_CONFIG_PHASE=1
    INVOCATION_ID=22ae2990007d464db91f1a6252bbd19e
    JOURNAL_STREAM=8:54369
    LANG=zh_CN.UTF-8
    LANGUAGE=zh_CN:zh
    LESSCLOSE=/usr/bin/lesspipe %s %s
    LESSOPEN=| /usr/bin/lesspipe %s
    LOGNAME=jshzt
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
    MANAGERPID=1548
    OLDPWD=/home/jshzt/code/SQL_apk
    ORIGINAL_XDG_CURRENT_DESKTOP=Unity
    PATH=/home/jshzt/miniconda3/envs/sqlapk/bin:/home/jshzt/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    PWD=/home/jshzt/code/SQL_apk/helloworld
    QT_ACCESSIBILITY=1
    QT_IM_MODULE=ibus
    SESSION_MANAGER=local/jshztcom:@/tmp/.ICE-unix/1896,unix/jshztcom:/tmp/.ICE-unix/1896
    SHELL=/bin/bash
    SHLVL=1
    SSH_AGENT_PID=1778
    SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
    TERM=xterm-256color
    TERM_PROGRAM=vscode
    TERM_PROGRAM_VERSION=1.73.1
    USER=jshzt
    USERNAME=jshzt
    VSCODE_GIT_ASKPASS_EXTRA_ARGS=********************
    VSCODE_GIT_ASKPASS_MAIN=********************
    VSCODE_GIT_ASKPASS_NODE=********************
    VSCODE_GIT_IPC_HANDLE=/run/user/1000/vscode-git-e0bf7b5a57.sock
    WINDOWPATH=2
    XAUTHORITY=/run/user/1000/gdm/Xauthority
    XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
    XDG_CURRENT_DESKTOP=Unity
    XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
    XDG_MENU_PREFIX=gnome-
    XDG_RUNTIME_DIR=/run/user/1000
    XDG_SESSION_CLASS=user
    XDG_SESSION_DESKTOP=ubuntu
    XDG_SESSION_TYPE=x11
    XMODIFIERS=@im=ibus
    _=/home/jshzt/miniconda3/envs/sqlapk/bin/briefcase
    _CE_CONDA=
    _CE_M=

Briefcase Log:
[22:38:05]                                                                                                                                                                dev.py:161
           [helloworld] Installing dependencies...                                                                                                                        dev.py:161
                                                                                                                                                                   subprocess.py:516
           >>> Running Command:                                                                                                                                    subprocess.py:517
           >>>     /home/jshzt/miniconda3/envs/sqlapk/bin/python -u -m pip install --upgrade 'toga-gtk>=0.3.0.dev38'                                               subprocess.py:518
           >>> Working Directory:                                                                                                                                  subprocess.py:525
           >>>     /home/jshzt/code/SQL_apk/helloworld                                                                                                             subprocess.py:526
           Requirement already satisfied: toga-gtk>=0.3.0.dev38 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (0.3.0.dev39)                    subprocess.py:495
[22:38:07] Requirement already satisfied: pycairo>=1.17.0 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (from toga-gtk>=0.3.0.dev38) (1.23.0)  subprocess.py:495
           Requirement already satisfied: pygobject>=3.14.0 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (from toga-gtk>=0.3.0.dev38)         subprocess.py:495
           (3.42.2)                                                                                                                                                                 
           Requirement already satisfied: toga-core==0.3.0.dev39 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (from toga-gtk>=0.3.0.dev38)    subprocess.py:495
           (0.3.0.dev39)                                                                                                                                                            
           Requirement already satisfied: gbulb>=0.5.3 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (from toga-gtk>=0.3.0.dev38) (0.6.3)      subprocess.py:495
           Requirement already satisfied: travertino>=0.1.3 in /home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages (from                                subprocess.py:495
           toga-core==0.3.0.dev39->toga-gtk>=0.3.0.dev38) (0.1.3)                                                                                                                   
           >>> Return code: 0                                                                                                                                      subprocess.py:553
           Installing dev dependencies... done                                                                                                                             dev.py:78
                                                                                                                                                                          dev.py:166
           [helloworld] Starting in dev mode...                                                                                                                           dev.py:166
                                                                                                                                                                   subprocess.py:516
           >>> Running Command:                                                                                                                                    subprocess.py:517
           >>>     /home/jshzt/miniconda3/envs/sqlapk/bin/python -u -c 'import runpy, sys;sys.path.pop(0);runpy.run_module("helloworld", run_name="__main__",      subprocess.py:518
           alter_sys=True)'                                                                                                                                                         
           >>> Working Directory:                                                                                                                                  subprocess.py:525
           >>>     /home/jshzt                                                                                                                                     subprocess.py:526
           >>> Environment Overrides:                                                                                                                              subprocess.py:535
           >>>     PYTHONPATH=/home/jshzt/code/SQL_apk/helloworld/src                                                                                              subprocess.py:537
           Traceback (most recent call last):                                                                                                                      subprocess.py:495
             File "<string>", line 1, in <module>                                                                                                                  subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/runpy.py", line 207, in run_module                                                             subprocess.py:495
               return _run_module_code(code, init_globals, run_name, mod_spec)                                                                                     subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/runpy.py", line 97, in _run_module_code                                                        subprocess.py:495
               _run_code(code, mod_globals, init_globals,                                                                                                          subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/runpy.py", line 87, in _run_code                                                               subprocess.py:495
               exec(code, run_globals)                                                                                                                             subprocess.py:495
             File "/home/jshzt/code/SQL_apk/helloworld/src/helloworld/__main__.py", line 4, in <module>                                                            subprocess.py:495
               main().main_loop()                                                                                                                                  subprocess.py:495
             File "/home/jshzt/code/SQL_apk/helloworld/src/helloworld/app.py", line 27, in main                                                                    subprocess.py:495
               return HelloWorld()                                                                                                                                 subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga/app.py", line 278, in __init__                                              subprocess.py:495
               self.factory = get_platform_factory(factory)                                                                                                        subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga/platform.py", line 43, in get_platform_factory                              subprocess.py:495
               from toga_gtk import factory                                                                                                                        subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga_gtk/factory.py", line 1, in <module>                                        subprocess.py:495
               from .app import App, DocumentApp, MainWindow                                                                                                       subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga_gtk/app.py", line 13, in <module>                                           subprocess.py:495
               from .keys import gtk_accel                                                                                                                         subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga_gtk/keys.py", line 3, in <module>                                           subprocess.py:495
               from .libs import Gdk                                                                                                                               subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga_gtk/libs/__init__.py", line 1, in <module>                                  subprocess.py:495
               from .gtk import *  # noqa: F401, F403                                                                                                              subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/toga_gtk/libs/gtk.py", line 1, in <module>                                       subprocess.py:495
               import gi                                                                                                                                           subprocess.py:495
             File "/home/jshzt/miniconda3/envs/sqlapk/lib/python3.8/site-packages/gi/__init__.py", line 40, in <module>                                            subprocess.py:495
               from . import _gi                                                                                                                                   subprocess.py:495
           ImportError: /lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0                                      subprocess.py:495
           >>> Return code: 1                                                                                                                                      subprocess.py:553
                                                                                                                                                                      __main__.py:27
           Unable to start application 'helloworld'                                                                                                                   __main__.py:28

```

**Comment by rmartin16** [comment]
Have you installed the OS dependencies? The tutorial runs for me on a fresh Ubuntu 20.04 with Python 3.8.15.

https://docs.beeware.org/en/latest/tutorial/tutorial-0.html#install-dependencies

**Comment by JSHZT** [comment]
I'm sure I've followed the steps of the tutorial, but I still can't solve it, now I'm developing on the window system

**Comment by freakboy3742** [comment]
@JSHZT It's very difficult to provide any advice or diagnostic help if you don't provide details. 

If you're getting a failure on Windows, it won't be the same problem as you're seeing on Linux - because Windows doesn't use libFFI as part of its integration. You'll need to provide the log file that is generated on Windows, along with any error messages that are being generated in the console. 

As for the original Linux error; can you clarify the exact Linux distribution you're using? The log suggests it is Ubuntu 20.04.1; but the error you're reporting suggests that you've got a different libffi than the one that ships with Ubuntu. This *might* be caused by miniconda shipping a version of libffi that isn't compatible with the GTK libraries installed on your system. Can you confirm the Conda packages that you have installed the active Conda environment?

**Comment by JSHZT** [comment]
@freakboy3742 well, Maybe it's my dependence that I didn't install correctly , but I do not know what I did wrong, I just ran the following command
` ` `
sudo apt-get install git python3-dev python3-venv python3-gi python3-gi-cairo libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0
pip install briefcase
` ` `
I run "conda list",The result is as follows:
` ` `
# packages in environment at /home/jshzt/miniconda3/envs/sqlapk:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
aom                       3.5.0                h27087fc_0    conda-forge
arrow                     1.2.3                    pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
briefcase                 0.3.11                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colosseum                 0.2.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cookiecutter              2.1.1                    pypi_0    pypi
dav1d                     1.0.0                h166bdaf_1    conda-forge
docutils                  0.19             py38h578d9bd_1    conda-forge
fluidsynth                2.2.8                h8d90f05_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gbulb                     0.6.3                    pypi_0    pypi
gettext                   0.21.1               h27087fc_0    conda-forge
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.21.2               hd4edc92_0    conda-forge
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.13.0                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
kivy                      2.1.0            py38h02b3273_2    conda-forge
kivy-garden               0.1.5                    pypi_0    pypi
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      4.0.0                h27087fc_0    conda-forge
libavif                   0.11.1               h5cdd6b5_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libffi                    3.4.2                h6a678d5_6    defaults
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmad                    0.15.1b           h14c3975_1000    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.6               he0ac6c6_0    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3    defaults
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1s               h0b41bf4_1    conda-forge
opusfile                  0.12                 hae46d1a_1    conda-forge
packaging                 21.3                     pypi_0    pypi
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    9.2.0            py38h9eb91d8_3    conda-forge
pip                       22.2.2           py38h06a4308_0    defaults
platformdirs              2.5.4                    pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycairo                   1.23.0                   pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pygobject                 3.42.2                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-slugify            7.0.0                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.1                   pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
sdl2                      2.0.22               h27087fc_1    conda-forge
sdl2_image                2.6.2                h916e60d_0    conda-forge
sdl2_mixer                2.6.2                h27087fc_0    conda-forge
sdl2_ttf                  2.0.15               h7d98c4e_0    conda-forge
setuptools                65.5.0           py38h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
smpeg2                    2.0.0                hfc679d8_1    conda-forge
sqlite                    3.40.0               h5082296_0    defaults
text-unidecode            1.3                      pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
toga                      0.2.15                   pypi_0    pypi
toga-core                 0.3.0.dev39              pypi_0    pypi
toga-gtk                  0.3.0.dev39              pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomli-w                   1.0.0                    pypi_0    pypi
travertino                0.1.3                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.8                h5eee18b_0    defaults
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
` ` `

**Comment by JSHZT** [comment]
@freakboy3742 well， I think maybe there is a problem with the steps I installed the library and dependencies, but I don't know what I did wrong, I just ran the following two commands
```
sudo apt-get install git python3-dev python3-venv python3-gi python3-gi-cairo libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0
pip install briefcase
```
and i run "conda list",the result is as follow:
```
# packages in environment at /home/jshzt/miniconda3/envs/sqlapk:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
aom                       3.5.0                h27087fc_0    conda-forge
arrow                     1.2.3                    pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
briefcase                 0.3.11                   pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colosseum                 0.2.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cookiecutter              2.1.1                    pypi_0    pypi
dav1d                     1.0.0                h166bdaf_1    conda-forge
docutils                  0.19             py38h578d9bd_1    conda-forge
fluidsynth                2.2.8                h8d90f05_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gbulb                     0.6.3                    pypi_0    pypi
gettext                   0.21.1               h27087fc_0    conda-forge
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.21.2               hd4edc92_0    conda-forge
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.13.0                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
kivy                      2.1.0            py38h02b3273_2    conda-forge
kivy-garden               0.1.5                    pypi_0    pypi
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      4.0.0                h27087fc_0    conda-forge
libavif                   0.11.1               h5cdd6b5_0    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libffi                    3.4.2                h6a678d5_6    defaults
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmad                    0.15.1b           h14c3975_1000    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.6               he0ac6c6_0    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3    defaults
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1s               h0b41bf4_1    conda-forge
opusfile                  0.12                 hae46d1a_1    conda-forge
packaging                 21.3                     pypi_0    pypi
pcre2                     10.40                hc3806b6_0    conda-forge
pillow                    9.2.0            py38h9eb91d8_3    conda-forge
pip                       22.2.2           py38h06a4308_0    defaults
platformdirs              2.5.4                    pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycairo                   1.23.0                   pypi_0    pypi
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pygobject                 3.42.2                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.8.15               h7a1cb2a_2    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-slugify            7.0.0                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.1                   pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
sdl2                      2.0.22               h27087fc_1    conda-forge
sdl2_image                2.6.2                h916e60d_0    conda-forge
sdl2_mixer                2.6.2                h27087fc_0    conda-forge
sdl2_ttf                  2.0.15               h7d98c4e_0    conda-forge
setuptools                65.5.0           py38h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
smpeg2                    2.0.0                hfc679d8_1    conda-forge
sqlite                    3.40.0               h5082296_0    defaults
text-unidecode            1.3                      pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    defaults
toga                      0.2.15                   pypi_0    pypi
toga-core                 0.3.0.dev39              pypi_0    pypi
toga-gtk                  0.3.0.dev39              pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomli-w                   1.0.0                    pypi_0    pypi
travertino                0.1.3                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.8                h5eee18b_0    defaults
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by freakboy3742** [comment]
Closing due to lack of response.
