### ISSUE TITLE
[ios simulator]  no module named 'numpy'

### ISSUE THREAD

**Issue by EVRH** [beeware/briefcase#999]
### Describe the bug

Briefcase update 0.3.10 brought binary package support "you only need to add them to the requires definition in your pyproject.toml, then update and re-build your project, and you're done.". However when I do just that, my app crashes when I try to run it.

### Steps to reproduce

1. Follow briefcase tutorial until end of step 5 (iOS)
2. Import numpy in app.py
3. Add numpy in pyproject.toml "requires"
4. briefcase update iOS
5. briefcase build iOS
6. briefcase run iOS

### Expected behavior

Tutorial app starts

### Environment

- Operating System: macOS Monterey (12.5.1) M1 Chip
- Python version: 3.10.8
- Software versions:
  - Briefcase: 0.3.11

### Logs

```
2022-12-12 16:08:06.053 Df Hello World[25529:6e624] (libffi.dylib)     import numpy as np
2022-12-12 16:08:06.053 Df Hello World[25529:6e624] (libffi.dylib) ModuleNotFoundError: No module named 'numpy'
2022-12-12 16:08:06.053 Df Hello World[25529:6e624] Traceback (most recent call last):
  File "Hello World.app/Contents/Resources/app/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
  File "Hello World.app/Contents/Resources/app/helloworld/app.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by rmartin16** [comment]
When the python dependencies change, you'll need to run `briefcase update ios -d` to ensure the new dependencies are installed. By default, `briefcase update` only updates your source code to be built.

**Comment by freakboy3742** [comment]
Closing on the basis that the error is in usage. Step 7 of the tutorial covers this use case.
